import logging

import bpy

from .utils import get_language_list


_LOGGER = logging.getLogger(__name__)


def origin_text(a, b):
    return "Add an empty object origin as the rotation axis (if there is an " \
           "origin, " + a + \
        "), and set the origin position " + b + " during operation"


not_add = "do not add it"
translations_dict = {
    "Rotation Mode": "\u65cb\u8f6c\u6a21\u5f0f",
    "Previous": "\u4e0a\u4e00\u4e2a",
    "Next": "\u4e0b\u4e00\u4e2a",
    "Select the previous Simple Deform modifier":
        "\u9009\u62e9\u4e0a\u4e00\u4e2a\u7b80\u6613\u5f62\u53d8\u4fee\u6539\u5668",
    "Select the next Simple Deform modifier":
        "\u9009\u62e9\u4e0b\u4e00\u4e2a\u7b80\u6613\u5f62\u53d8\u4fee\u6539\u5668",
    "Earlier": "\u66f4\u65e9",
    "Later": "\u66f4\u665a",
    "Tool Settings": "\u5de5\u5177\u8bbe\u7f6e",
    "In Front": "\u663e\u793a\u5728\u524d\u65b9",
    "Show Gizmo": "\u663e\u793a Gizmo",
    "Stage Index": "\u9636\u6bb5\u7d22\u5f15",
    "Active Deformation Layer": "\u6d3b\u52a8\u5f62\u53d8\u5c42",
    "Muted Deformations": "\u5df2\u9759\u97f3\u7684\u5f62\u53d8",
    "Original Origin": "\u539f\u59cb\u539f\u70b9",
    "Origin Object Rotate Angle": "\u539f\u70b9\u5bf9\u8c61\u65cb\u8f6c\u89d2\u5ea6",
    "Origin Object Rotate Axis": "\u539f\u70b9\u5bf9\u8c61\u65cb\u8f6c\u8f74",
    "Expand every deformation layer in the cage UI":
        "\u5728\u7b3c\u9762\u677f\u4e2d\u5c55\u5f00\u6240\u6709\u5f62\u53d8\u5c42",
    "Persistent execution order for the enabled deformation layers":
        "\u4fdd\u5b58\u5df2\u542f\u7528\u5f62\u53d8\u5c42\u7684\u6267\u884c\u987a\u5e8f",
    "Index of the deformation layer selected in the cage UI":
        "\u7b3c\u9762\u677f\u4e2d\u9009\u4e2d\u7684\u5f62\u53d8\u5c42\u7d22\u5f15",
    "Present deformation layers temporarily bypassed by this cage":
        "\u6b64\u7b3c\u4e34\u65f6\u8df3\u8fc7\u7684\u73b0\u6709\u5f62\u53d8\u5c42",
    "Temporarily bypass Bend": "\u4e34\u65f6\u8df3\u8fc7\u5f2f\u66f2",
    "Temporarily bypass Twist": "\u4e34\u65f6\u8df3\u8fc7\u626d\u8f6c",
    "Temporarily bypass Taper": "\u4e34\u65f6\u8df3\u8fc7\u9525\u5316",
    "Temporarily bypass Stretch": "\u4e34\u65f6\u8df3\u8fc7\u62c9\u4f38",
    "Move before the previous Cage Deform":
        "\u79fb\u52a8\u5230\u4e0a\u4e00\u4e2a\u7b3c\u5f0f\u5f62\u53d8\u4e4b\u524d",
    "Move after the next Cage Deform":
        "\u79fb\u52a8\u5230\u4e0b\u4e00\u4e2a\u7b3c\u5f0f\u5f62\u53d8\u4e4b\u540e",
    "Key the active strength, limits, and managed Origin controls":
        "\u4e3a\u6d3b\u52a8\u5f3a\u5ea6\u3001\u9650\u5236\u548c\u53d7\u7ba1\u7406\u539f\u70b9\u63a7\u5236\u63d2\u5165\u5173\u952e\u5e27",
    "Remove the current-frame keys created for the active Simple Deform":
        "\u5220\u9664\u6d3b\u52a8\u7b80\u6613\u5f62\u53d8\u521b\u5efa\u7684\u5f53\u524d\u5e27\u5173\u952e\u5e27",
    "Create a managed Origin and keep it at the upper limit while dragging":
        "\u521b\u5efa\u53d7\u7ba1\u7406\u7684\u539f\u70b9\uff0c\u5e76\u5728\u62d6\u52a8\u65f6\u5c06\u5176\u4fdd\u6301\u5728\u4e0a\u9650",
    "Create a managed Origin and keep it at the lower limit while dragging":
        "\u521b\u5efa\u53d7\u7ba1\u7406\u7684\u539f\u70b9\uff0c\u5e76\u5728\u62d6\u52a8\u65f6\u5c06\u5176\u4fdd\u6301\u5728\u4e0b\u9650",
    "Create a managed Origin between the upper and lower limits":
        "\u5728\u4e0a\u9650\u4e0e\u4e0b\u9650\u4e4b\u95f4\u521b\u5efa\u53d7\u7ba1\u7406\u7684\u539f\u70b9",
    "Create a managed Origin at the deformation bounds center":
        "\u5728\u5f62\u53d8\u8fb9\u754c\u6846\u4e2d\u5fc3\u521b\u5efa\u53d7\u7ba1\u7406\u7684\u539f\u70b9",
    "Middle": "\u4e2d\u95f4",
    "Stage {stage_index} of {stage_count}: {modifier}":
        "\u7b2c {stage_index} / {stage_count} \u4e2a\u9636\u6bb5\uff1a{modifier}",
    "Deform {stage_index}/{stage_count}":
        "\u5f62\u53d8 {stage_index}/{stage_count}",
    "Low topology on {axis}: {sample_count} levels":
        "{axis} \u8f74\u62d3\u6251\u5bc6\u5ea6\u8fc7\u4f4e\uff1a{sample_count} \u4e2a\u5c42\u7ea7",
    "Animated": "\u52a8\u753b",
    "Property": "\u5c5e\u6027",
    "01 Local Space": "01 \u5c40\u90e8\u7a7a\u95f4",
    "02 Cage Profile": "02 \u7b3c\u8f6e\u5ed3",
    "07 Mode and Output": "07 \u6a21\u5f0f\u4e0e\u8f93\u51fa",
    "Subdivide to Chained Cages": "\u7ec6\u5206\u4e3a\u94fe\u5f0f\u7b3c",
    "Split the active cage inside its current range and distribute its deformation across a chained cage stack":
        "\u5728\u5f53\u524d\u7b3c\u8303\u56f4\u5185\u8fdb\u884c\u7ec6\u5206\uff0c\u5e76\u5c06\u5f62\u53d8\u5206\u914d\u5230\u94fe\u5f0f\u7b3c\u5806\u6808",
    "Number of chained segments inside the current cage range":
        "\u5f53\u524d\u7b3c\u8303\u56f4\u5185\u7684\u94fe\u5f0f\u5206\u6bb5\u6570\u91cf",
    "Uniform spacing between segments; segment lengths shrink so the original total range is preserved":
        "\u5206\u6bb5\u4e4b\u95f4\u7684\u7edf\u4e00\u95f4\u9694\uff1b\u5206\u6bb5\u957f\u5ea6\u4f1a\u76f8\u5e94\u7f29\u77ed\uff0c\u4ee5\u4fdd\u6301\u539f\u59cb\u603b\u8303\u56f4",
    "Keep each newly-created shared cross-section continuous":
        "\u4fdd\u6301\u65b0\u5efa\u5171\u4eab\u622a\u9762\u8fde\u7eed",
    "The original cage boundaries stay fixed.":
        "\u539f\u7b3c\u7684\u9996\u5c3e\u8fb9\u754c\u4fdd\u6301\u4e0d\u53d8\u3002",
    "Bend and Twist angles are distributed across segments.":
        "\u5f2f\u66f2\u4e0e\u626d\u8f6c\u89d2\u5ea6\u4f1a\u5206\u914d\u5230\u5404\u4e2a\u5206\u6bb5\u3002",
    "Batch Edit": "\u6279\u91cf\u7f16\u8f91",
    "Batch Edit Chain": "\u6279\u91cf\u7f16\u8f91\u94fe\u5f0f\u7b3c",
    "Edit several cages in the active chain as one operation":
        "\u5728\u4e00\u6b21\u64cd\u4f5c\u4e2d\u7f16\u8f91\u5f53\u524d\u94fe\u4e2d\u7684\u591a\u4e2a\u7b3c",
    "Scope": "\u8303\u56f4",
    "Whole Chain": "\u6574\u6761\u94fe",
    "Edit every cage in this chain": "\u7f16\u8f91\u6b64\u94fe\u4e2d\u7684\u6240\u6709\u7b3c",
    "Start to Active": "\u8d77\u70b9\u5230\u5f53\u524d",
    "Edit the chain root through the active cage":
        "\u7f16\u8f91\u4ece\u94fe\u6839\u5230\u5f53\u524d\u7b3c",
    "Active to End": "\u5f53\u524d\u5230\u672b\u7aef",
    "Edit the active cage through the chain tip":
        "\u7f16\u8f91\u4ece\u5f53\u524d\u7b3c\u5230\u94fe\u672b\u7aef",
    "Operation": "\u64cd\u4f5c",
    "End Scale": "\u7aef\u90e8\u7f29\u653e",
    "Batch-edit top and bottom cross-section scale":
        "\u6279\u91cf\u7f16\u8f91\u9876\u90e8\u4e0e\u5e95\u90e8\u622a\u9762\u7f29\u653e",
    "End Offset": "\u7aef\u90e8\u504f\u79fb",
    "Batch-edit top and bottom cross-section offset":
        "\u6279\u91cf\u7f16\u8f91\u9876\u90e8\u4e0e\u5e95\u90e8\u622a\u9762\u504f\u79fb",
    "Set spacing before every cage in scope":
        "\u8bbe\u7f6e\u8303\u56f4\u5185\u6bcf\u4e2a\u7b3c\u4e4b\u524d\u7684\u95f4\u9694",
    "Batch-edit one deformation parameter":
        "\u6279\u91cf\u7f16\u8f91\u4e00\u4e2a\u5f62\u53d8\u53c2\u6570",
    "Deformation": "\u5f62\u53d8",
    "Stage Visibility": "\u5f62\u53d8\u6bb5\u542f\u7528\u72b6\u6001",
    "Apply or bypass every cage in scope":
        "\u5e94\u7528\u6216\u8df3\u8fc7\u8303\u56f4\u5185\u7684\u6bcf\u4e2a\u7b3c",
    "Ends": "\u7aef\u90e8",
    "Edit top ends": "\u7f16\u8f91\u9876\u90e8",
    "Edit bottom ends": "\u7f16\u8f91\u5e95\u90e8",
    "Both": "\u4e24\u7aef",
    "Edit both ends": "\u540c\u65f6\u7f16\u8f91\u4e24\u7aef",
    "Apply As": "\u5e94\u7528\u65b9\u5f0f",
    "Set Values": "\u8bbe\u7f6e",
    "Replace existing values": "\u66ff\u6362\u73b0\u6709\u503c",
    "Add Values": "\u53e0\u52a0",
    "Add to existing values": "\u4e0e\u73b0\u6709\u503c\u76f8\u52a0",
    "Multiply Values": "\u4e58\u7b97",
    "Multiply existing values": "\u4e0e\u73b0\u6709\u503c\u76f8\u4e58",
    "X and Z cross-section values": "\u622a\u9762 X \u4e0e Z \u503c",
    "X and Z cross-section offset values": "\u622a\u9762 X \u4e0e Z \u504f\u79fb\u503c",
    "Spacing before each affected downstream cage":
        "\u6bcf\u4e2a\u53d7\u5f71\u54cd\u4e0b\u6e38\u7b3c\u4e4b\u524d\u7684\u95f4\u9694",
    "Preserve Total Range": "\u4fdd\u6301\u603b\u8303\u56f4",
    "Shorten each cage as its incoming gap grows":
        "\u5728\u524d\u95f4\u9694\u589e\u5927\u65f6\u76f8\u5e94\u7f29\u77ed\u7b3c",
    "Parameter": "\u53c2\u6570",
    "Batch-edit Bend angle": "\u6279\u91cf\u7f16\u8f91\u5f2f\u66f2\u89d2\u5ea6",
    "Batch-edit Bend direction": "\u6279\u91cf\u7f16\u8f91\u5f2f\u66f2\u65b9\u5411",
    "Batch-edit Twist angle": "\u6279\u91cf\u7f16\u8f91\u626d\u8f6c\u89d2\u5ea6",
    "Batch-edit Taper factor": "\u6279\u91cf\u7f16\u8f91\u9525\u5316\u7cfb\u6570",
    "Batch-edit Stretch factor": "\u6279\u91cf\u7f16\u8f91\u62c9\u4f38\u7cfb\u6570",
    "Enable Stages": "\u542f\u7528\u5f62\u53d8\u6bb5",
    "Apply the affected cage stages": "\u5e94\u7528\u53d7\u5f71\u54cd\u7684\u7b3c\u5f62\u53d8\u6bb5",
    "Linked shared boundaries are changed only once.":
        "\u5df2\u8054\u52a8\u7684\u5171\u4eab\u8fb9\u754c\u53ea\u4f1a\u66f4\u6539\u4e00\u6b21\u3002",
    "Cages without this deformation layer are skipped.":
        "\u4e0d\u542b\u6b64\u5f62\u53d8\u5c42\u7684\u7b3c\u4f1a\u88ab\u8df3\u8fc7\u3002",
    "Created {count} cage stages": "\u5df2\u521b\u5efa {count} \u4e2a\u7b3c\u9636\u6bb5",
    "Could not create cage chain: {error}": "\u65e0\u6cd5\u521b\u5efa\u7b3c\u94fe\uff1a{error}",
    "Only a single cage can be subdivided": "\u53ea\u80fd\u7ec6\u5206\u5355\u4e2a\u7b3c",
    "Set the cage origin to Bottom before subdividing":
        "\u7ec6\u5206\u524d\u8bf7\u5c06\u7b3c\u7684\u8d77\u70b9\u8bbe\u4e3a\u5e95\u90e8",
    "Animated cage parameters cannot be subdivided safely":
        "\u5e26\u52a8\u753b\u7684\u7b3c\u53c2\u6570\u65e0\u6cd5\u5b89\u5168\u7ec6\u5206",
    "Taper collapses at an interior split boundary":
        "\u9525\u5316\u4f1a\u5728\u5185\u90e8\u5206\u5272\u8fb9\u754c\u5904\u584c\u9677",
    "Subdivided cage into {count} chained stages":
        "\u5df2\u5c06\u7b3c\u7ec6\u5206\u4e3a {count} \u4e2a\u94fe\u5f0f\u9636\u6bb5",
    "Subdivided cage into {count} chained stages (gap clamped to preserve range)":
        "\u5df2\u5c06\u7b3c\u7ec6\u5206\u4e3a {count} \u4e2a\u94fe\u5f0f\u9636\u6bb5\uff08\u95f4\u9694\u5df2\u9650\u5236\u4ee5\u4fdd\u6301\u8303\u56f4\uff09",
    "Could not subdivide cage: {error}": "\u65e0\u6cd5\u7ec6\u5206\u7b3c\uff1a{error}",
    "Could not batch edit chain: {error}": "\u65e0\u6cd5\u6279\u91cf\u7f16\u8f91\u7b3c\u94fe\uff1a{error}",
    "No matching cage values were changed": "\u6ca1\u6709\u7b26\u5408\u6761\u4ef6\u7684\u7b3c\u53c2\u6570\u88ab\u66f4\u6539",
    "Updated {count} cage stages": "\u5df2\u66f4\u65b0 {count} \u4e2a\u7b3c\u9636\u6bb5",
    "Fitted {count} cage stages to chain input":
        "\u5df2\u5c06 {count} \u4e2a\u7b3c\u9636\u6bb5\u9002\u914d\u5230\u7b3c\u94fe\u8f93\u5165",
    "No cage chain metadata was found": "\u672a\u627e\u5230\u7b3c\u94fe\u5143\u6570\u636e",
    "Missing cage stages: {indices}": "\u7f3a\u5c11\u7b3c\u9636\u6bb5\uff1a{indices}",
    "Duplicate cage stage indices: {indices}": "\u7b3c\u9636\u6bb5\u7d22\u5f15\u91cd\u590d\uff1a{indices}",
    "A non-cage modifier is inserted inside the chain":
        "\u7b3c\u94fe\u4e2d\u63d2\u5165\u4e86\u975e\u7b3c\u5f0f\u4fee\u6539\u5668",
    "A chain stage has no matching controller":
        "\u7b3c\u94fe\u9636\u6bb5\u7f3a\u5c11\u5339\u914d\u7684\u63a7\u5236\u5668",
    "Chain stages use different connection modes":
        "\u7b3c\u94fe\u9636\u6bb5\u4f7f\u7528\u4e86\u4e0d\u540c\u7684\u8fde\u63a5\u6a21\u5f0f",
    "Cage chain is broken": "\u7b3c\u94fe\u5df2\u65ad\u5f00",
    "No Cage Chain was found": "\u672a\u627e\u5230\u7b3c\u94fe",
    "Reconnected {count} cage stages": "\u5df2\u91cd\u65b0\u8fde\u63a5 {count} \u4e2a\u7b3c\u9636\u6bb5",
    "Add Cage Chain": "\u6dfb\u52a0\u7b3c\u94fe",
    "Number of segments to create": "\u8981\u521b\u5efa\u7684\u5206\u6bb5\u6570\u91cf",
    "Connection Mode": "\u8fde\u63a5\u6a21\u5f0f",
    "How neighboring cage segments handle their boundaries":
        "\u76f8\u90bb\u7b3c\u6bb5\u5982\u4f55\u5904\u7406\u8fb9\u754c",
    "Continue from each preceding cage":
        "\u4ece\u524d\u4e00\u4e2a\u7b3c\u7ee7\u7eed\u5ef6\u4f38",
    "Limit each segment to its own box":
        "\u5c06\u6bcf\u4e2a\u6bb5\u9650\u5236\u5728\u81ea\u8eab\u7b3c\u5185",
    "Gap": "\u95f4\u9694",
    "Gap Before": "前间隔",
    "Gap from Previous Cage": "与前一个笼的间隔",
    "Non-negative distance from the previous cage; changing it keeps the overall chain span when possible":
        "与前一个笼之间的非负距离；调整时会尽可能保持笼链总跨度不变",
    "Distance between this cage and the previous cage":
        "当前笼与前一个笼之间的距离",
    "Distance between neighboring cage frames in target units":
        "\u76f8\u90bb\u7b3c\u6846\u4e4b\u95f4\u7684\u8ddd\u79bb\uff08\u76ee\u6807\u7269\u4f53\u5355\u4f4d\uff09",
    "Cage Axis": "\u7b3c\u8f74\u5411",
    "Use the longest input dimension": "\u4f7f\u7528\u8f93\u5165\u51e0\u4f55\u7684\u6700\u957f\u5c3a\u5bf8",
    "Align cage Y to target +X": "\u5c06\u7b3c Y \u8f74\u5bf9\u9f50\u5230\u76ee\u6807 +X",
    "Align cage Y to target -X": "\u5c06\u7b3c Y \u8f74\u5bf9\u9f50\u5230\u76ee\u6807 -X",
    "Align cage Y to target +Y": "\u5c06\u7b3c Y \u8f74\u5bf9\u9f50\u5230\u76ee\u6807 +Y",
    "Align cage Y to target -Y": "\u5c06\u7b3c Y \u8f74\u5bf9\u9f50\u5230\u76ee\u6807 -Y",
    "Align cage Y to target +Z": "\u5c06\u7b3c Y \u8f74\u5bf9\u9f50\u5230\u76ee\u6807 +Z",
    "Align cage Y to target -Z": "\u5c06\u7b3c Y \u8f74\u5bf9\u9f50\u5230\u76ee\u6807 -Z",
    "Select a supported target object first": "\u8bf7\u5148\u9009\u62e9\u652f\u6301\u7684\u76ee\u6807\u5bf9\u8c61",
    "Add Simple Deform": "\u6dfb\u52a0\u7b80\u6613\u5f62\u53d8",
    "Add Simple Deform (Legacy)":
        "\u6dfb\u52a0\u7b80\u6613\u5f62\u53d8\u4fee\u6539\u5668\uff08\u4f20\u7edf\uff09",
    "Add a traditional Simple Deform modifier":
        "\u6dfb\u52a0\u4f20\u7edf\u7b80\u6613\u5f62\u53d8\u4fee\u6539\u5668",
    "Added legacy Simple Deform modifier":
        "\u5df2\u6dfb\u52a0\u4f20\u7edf\u7b80\u6613\u5f62\u53d8\u4fee\u6539\u5668",
    "Cage deformation is not supported for lattice objects":
        "\u6676\u683c\u7269\u4f53\u5f53\u524d\u4e0d\u652f\u6301\u7b3c\u5f0f\u5f62\u53d8",
    "The selected surface could not be converted for cage deformation":
        "\u9009\u4e2d\u7684\u66f2\u9762\u65e0\u6cd5\u8f6c\u6362\u4e3a\u7b3c\u5f0f\u53d8\u5f62\u6240\u9700\u7684\u7f51\u683c",
    "Surface cage deformation requires a mesh conversion":
        "\u66f2\u9762\u7b3c\u5f0f\u53d8\u5f62\u9700\u8981\u5148\u8f6c\u6362\u4e3a\u7f51\u683c",
    "Add Chained Cages": "\u6dfb\u52a0\u94fe\u5f0f\u7b3c",
    "Create Cage Chain": "\u521b\u5efa\u7b3c\u94fe",
    "Create several related deformation cages in one operation":
        "\u4e00\u6b21\u521b\u5efa\u591a\u4e2a\u76f8\u5173\u53d8\u5f62\u7b3c",
    "Cage Count": "\u7b3c\u6570\u91cf",
    "Use isolated boxes": "\u4ec5\u5f71\u54cd\u5404\u81ea\u7b3c\u6846\u5185\u7684\u51e0\u4f55\u4f53",
    "Number of chained cages to create": "\u8981\u521b\u5efa\u7684\u94fe\u5f0f\u7b3c\u6570\u91cf",
    "Connect Ends": "\u8fde\u63a5\u7aef\u90e8",
    "Align each cage bottom to the previous cage top":
        "\u5c06\u6bcf\u4e2a\u7b3c\u7684\u5e95\u90e8\u5bf9\u9f50\u5230\u524d\u4e00\u4e2a\u7b3c\u7684\u9876\u90e8",
    "Chain Mode": "\u7b3c\u94fe\u6a21\u5f0f",
    "Use forward continuation when available":
        "\u5c3d\u53ef\u80fd\u4f7f\u7528\u6cbf\u524d\u65b9\u8fde\u7eed\u5ef6\u4f38",
    "Create stages without automatic reconnection":
        "\u521b\u5efa\u5404\u9636\u6bb5\uff0c\u4e0d\u81ea\u52a8\u91cd\u65b0\u8fde\u63a5",
    "Chained": "\u94fe\u5f0f",
    "Independent": "\u72ec\u7acb",
    "Segment": "\u6bb5",
    "Enable Stage": "\u542f\u7528\u5f62\u53d8\u6bb5",
    "Temporarily apply or bypass this cage while preserving chained-stage flow":
        "\u4e34\u65f6\u5e94\u7528\u6216\u8df3\u8fc7\u6b64\u7b3c\uff0c\u540c\u65f6\u4fdd\u6301\u94fe\u5f0f\u5f62\u53d8\u6bb5\u7684\u4f20\u9012",
    "Show Other Cages": "\u663e\u793a\u5176\u4ed6\u7b3c",
    "Display inactive cages and make their viewport controls directly editable":
        "\u663e\u793a\u975e\u5f53\u524d\u7b3c\uff0c\u5e76\u53ef\u76f4\u63a5\u7f16\u8f91\u5176\u89c6\u53e3\u63a7\u5236\u5668",
    "Show Other Cage Controllers": "\u663e\u793a\u5176\u4ed6\u7b3c\u63a7\u5236\u5668",
    "Display all cage controllers except active one":
        "\u663e\u793a\u9664\u5f53\u524d\u7b3c\u5916\u7684\u6240\u6709\u7b3c\u63a7\u5236\u5668",
    "Active Cage": "\u5f53\u524d\u7b3c",
    "Inactive Cage": "\u975e\u6d3b\u52a8\u7b3c",
    "Active cage is highlighted; other cages are dimmed":
        "\u5f53\u524d\u7b3c\u9ad8\u4eae\u663e\u793a\uff1b\u5176\u4ed6\u7b3c\u53d8\u6697",
    "Select this cage stage and its controller":
        "\u9009\u62e9\u6b64\u7b3c\u9636\u6bb5\u53ca\u5176\u63a7\u5236\u5668",
    "Select Cage Stage": "\u9009\u62e9\u7b3c\u9636\u6bb5",
    "Cage Deform Strength Handle": "\u7b3c\u5f0f\u53d8\u5f62\u5f3a\u5ea6\u624b\u67c4",
    "Cage End Shape": "\u7b3c\u7aef\u90e8\u5f62\u6001",
    "Cage Boundary": "\u7b3c\u8fb9\u754c",
    "Auto Reconnect Chain": "\u81ea\u52a8\u91cd\u65b0\u8fde\u63a5\u7b3c\u94fe",
    "Automatically refresh downstream cage frames after a chain parameter or controller transform changes":
        "\u94fe\u53c2\u6570\u6216\u63a7\u5236\u5668\u53d8\u6362\u540e\u81ea\u52a8\u5237\u65b0\u4e0b\u6e38\u7b3c\u6846",
    "Auto Reconnect": "\u81ea\u52a8\u91cd\u65b0\u8fde\u63a5",
    "Refresh downstream cage frames after upstream edits":
        "\u4e0a\u6e38\u7f16\u8f91\u540e\u5237\u65b0\u4e0b\u6e38\u7b3c\u6846",
    "Use one-sided continuation": "\u4f7f\u7528\u5355\u5411\u8fde\u7eed\u5ef6\u4f38",
    "Propagate each preceding cage output frame to the next cage":
        "\u5c06\u524d\u4e00\u4e2a\u7b3c\u7684\u8f93\u51fa\u6846\u4f20\u9012\u7ed9\u4e0b\u4e00\u4e2a\u7b3c",
    "Reconnect Broken Chain": "\u91cd\u65b0\u8fde\u63a5\u65ad\u88c2\u7b3c\u94fe",
    "Attempt contiguous stages even when a stack issue is detected":
        "\u5373\u4f7f\u5806\u6808\u5b58\u5728\u95ee\u9898\uff0c\u4e5f\u5c1d\u8bd5\u8fde\u7eed\u9636\u6bb5",
    "Cage Deform core is unavailable": "\u7b3c\u5f0f\u53d8\u5f62\u6838\u5fc3\u4e0d\u53ef\u7528",
    "Chained Cages": "\u94fe\u5f0f\u7b3c",
    "Independent Cage Chain": "\u72ec\u7acb\u7b3c\u94fe",
    "Reconnect Chain": "\u91cd\u65b0\u8fde\u63a5\u7b3c\u94fe",
    "Reconnect Cage Chain": "\u91cd\u65b0\u8fde\u63a5\u7b3c\u94fe",
    "Align each cage to the previous cage's output frame":
        "\u5c06\u6bcf\u4e2a\u7b3c\u5bf9\u9f50\u5230\u524d\u4e00\u4e2a\u7b3c\u7684\u8f93\u51fa\u6846",
    "Each stage keeps its own angle and length; reconnect updates the incoming frame.":
        "\u6bcf\u4e2a\u9636\u6bb5\u4fdd\u7559\u81ea\u8eab\u7684\u89d2\u5ea6\u548c\u957f\u5ea6\uff1b\u91cd\u65b0\u8fde\u63a5\u53ea\u66f4\u65b0\u8f93\u5165\u6846",
    "Each stage keeps its deformations, length, and incoming gap.":
        "每个阶段保留自身的形变、长度和前间隔。",
    "Sync Shared End Scale": "同步接缝端部缩放",
    "Scale both sides of each shared cage seam together while keeping each outer end independent":
        "同步每个相邻笼接缝两侧的端部缩放，同时保持首尾外端独立",
    "Scale both sides of each shared cage seam together while keeping outer ends independent":
        "同步每个相邻笼接缝两侧的端部缩放，同时保持外端独立",
    "Only neighboring seam-end scales are synchronized.":
        "仅同步相邻笼接缝端部的缩放。",
    "Outer cage ends remain independent.": "首尾外端仍保持独立。",
    "Chained mode starts at the lower cage boundary.":
        "\u94fe\u5f0f\u6a21\u5f0f\u4ece\u7b3c\u7684\u5e95\u90e8\u8fb9\u754c\u5f00\u59cb",
    "Cage Chain mode is locked to Chained.":
        "\u7b3c\u94fe\u6a21\u5f0f\u5df2\u9501\u5b9a\u4e3a\u94fe\u5f0f",
    "Keep the prefix unchanged and continue from the cage end":
        "\u4fdd\u6301\u524d\u6bb5\u4e0d\u53d8\uff0c\u4ece\u7b3c\u9876\u6cbf\u672b\u7aef\u8d8b\u52bf\u5ef6\u7eed",
    "Simple Deformer": "简易变形器",
    "Simple Deformer V2": "\u7b80\u6613\u53d8\u5f62\u5668V2",
    "Add New Cages to End": "\u5c06\u65b0\u7b3c\u6dfb\u52a0\u5230\u5806\u6808\u672b\u5c3e",
    "Place newly-created cage stages at the end of the modifier stack":
        "\u5c06\u65b0\u5efa\u7b3c\u9636\u6bb5\u653e\u5230\u4fee\u6539\u5668\u5806\u6808\u672b\u5c3e",
    "Cage Deform": "笼式形变",
    "Add Cage Deform": "添加笼式形变",
    "Add an independent cage deformation stage": "添加一个独立的笼式形变阶段",
    "Added Cage Deform stage": "已添加笼式形变阶段",
    "Deform axis changed; the user-supplied Origin was preserved":
        "形变轴已更改；已保留用户指定的原点",
    "Subdivision was added at the end; move it before Simple Deform":
        "细分已添加到末尾；请将其移动到简易形变之前",
    "Inserted {inserted} Simple Deform keyframe channels":
        "已插入 {inserted} 个简易形变关键帧通道",
    "Removed {removed} Simple Deform keyframe channels":
        "已删除 {removed} 个简易形变关键帧通道",
    "Independent cage deformation": "独立笼式形变",
    "Bend, Twist, Taper, and Stretch.": "支持弯曲、扭转、锥化和拉伸。",
    "Combine Bend, Twist, Taper, and Stretch in one cage.":
        "可在同一个笼中组合弯曲、扭曲、锥化和拉伸。",
    "Cage Stack": "笼式形变堆栈",
    "Move Cage Stage": "移动笼式形变阶段",
    "Move this deformation earlier or later in the modifier stack":
        "在修改器堆栈中前移或后移此形变",
    "Duplicate Cage Stage": "复制笼式形变阶段",
    "Duplicate": "复制",
    "Remove Cage Stage": "删除笼式形变阶段",
    "Remove Stage": "删除阶段",
    "Remove Cage Stack": "删除笼式堆栈",
    "Remove": "删除",
    "Remove this managed deformation stage and its cage controller":
        "删除此形变阶段及其笼控制器",
    "Remove every managed cage stage and its owned controllers":
        "删除所有受管笼式阶段及其控制器",
    "Shape": "形态",
    "Deformation Layers": "形变层",
    "Expand All": "\u5168\u90e8\u5c55\u5f00",
    "Add Deformation": "添加形变",
    "Add Deformation Layer": "添加形变层",
    "Add one deformation operation to this cage": "向当前笼添加一个形变操作",
    "Select Deformation Layer": "选择形变层",
    "Select this deformation layer without changing its evaluation":
        "选择此形变层，但不改变其计算状态",
    "Remove Deformation Layer": "移除形变层",
    "Remove this deformation operation from the cage": "从当前笼移除此形变操作",
    "Toggle Deformation Layer": "切换形变层启用状态",
    "Temporarily bypass or restore this deformation without losing its settings":
        "临时旁路或恢复此形变，并保留其设置",
    "Move Deformation Layer": "移动形变层",
    "Move this deformation operation earlier or later": "将此形变操作前移或后移",
    "Up": "上移",
    "Down": "下移",
    "Execute this layer earlier": "让此形变层更早执行",
    "Execute this layer later": "让此形变层更晚执行",
    "This deformation is already enabled": "此形变已启用",
    "Deformation Type": "形变类型",
    "Deformation Types": "形变类型",
    "Deformations": "形变组合",
    "Shape operations combined by this cage": "由当前笼组合执行的形变操作",
    "Enable one or more deformation operations in this cage":
        "在此笼中启用一种或多种形变操作",
    "At least one deformation type must remain enabled":
        "必须至少保留一种已启用的形变类型",
    "Shape operation performed inside the cage": "在笼范围内执行的形态操作",
    "Bend": "弯曲",
    "Curve geometry along the cage axis": "沿笼轴线弯曲几何体",
    "Twist": "扭曲",
    "Rotate cross-sections around the cage axis": "让横截面围绕笼轴线旋转",
    "Taper": "锥化",
    "Scale cross-sections along the cage axis": "沿笼轴线缩放横截面",
    "Stretch": "拉伸",
    "Scale geometry along the cage axis": "沿笼轴线缩放几何体",
    "Angle": "角度",
    "Total Bend or Twist angle through the cage length": "贯穿笼长度的弯曲或扭转总角度",
    "Bend Strength": "弯曲角度",
    "Bend angle through the cage length": "贯穿笼长度的弯曲角度",
    "Bend Angle": "弯曲角度",
    "Total Bend angle through the cage length": "贯穿笼长度的弯曲总角度",
    "Twist Strength": "扭曲角度",
    "Twist angle through the cage length": "贯穿笼长度的扭曲角度",
    "Twist Angle": "扭曲角度",
    "Total Twist angle through the cage length": "贯穿笼长度的扭曲总角度",
    "Taper Factor": "锥化系数",
    "Amount of taper along the cage axis": "沿笼轴向的锥化量",
    "Cross-section scale change through the cage length":
        "贯穿笼长度的横截面缩放变化量",
    "Stretch Factor": "拉伸系数",
    "Amount of stretch along the cage axis": "沿笼轴向的拉伸量",
    "Length scale change through the cage": "贯穿笼长度的轴向缩放变化量",
    "Factor": "系数",
    "Amount used by Taper and Stretch": "锥化和拉伸所使用的形变量",
    "Direction": "方向",
    "Direction of Bend around the cage axis": "围绕笼轴线的弯曲方向",
    "Mode": "范围模式",
    "How geometry outside the cage is handled": "决定如何处理笼外的几何体",
    "Limited": "受限",
    "Deform inside; continue outside from the cage ends":
        "笼内形变，笼外从两端延续末端趋势",
    "Within Box": "框内",
    "Only points inside the cage are affected": "只影响笼内的点",
    "Unlimited": "无限",
    "Continue deformation beyond the cage": "将形变连续延伸到笼外",
    "Origin": "起点",
    "Starting pattern of the deformation": "形变的起始方式",
    "Bottom": "底部",
    "Start at the lower cage boundary": "从笼的下边界开始",
    "Center": "中心",
    "Use signed distance from the cage center": "以笼中心的有符号距离作为起点",
    "Symmetric": "对称",
    "Mirror the deformation profile across the center": "让形变轮廓以中心镜像",
    "Top": "顶部",
    "Start at the upper cage boundary": "从笼的上边界开始",
    "Preserve Volume": "维持体积",
    "Compensate cross-section size while stretching": "拉伸时补偿横截面尺寸",
    "Cage Controls": "笼控制",
    "Deform Axis": "形变轴",
    "Target axis used when aligning and fitting the cage": "对齐和适配笼时使用的目标轴",
    "Size": "尺寸",
    "Dimensions of the independent deformation cage": "独立形变笼的尺寸",
    "Auto": "自动",
    "Use the longest local dimension": "使用最长的局部尺寸",
    "Align & Fit": "对齐并适配",
    "Align & Fit Chain": "对齐并适配链式笼",
    "Fit to Object": "适配物体",
    "Fit the active cage, or its entire connected chain, to the geometry entering the deformation":
        "将当前笼或其整条相连链式笼适配到进入形变的几何体",
    "Select Cage": "选择笼",
    "Select Cage Controller": "选择笼控制器",
    "Return to Object": "返回物体",
    "Select the object controlled by this deformation cage": "选择此形变笼所控制的物体",
    "Edit Cage": "编辑笼",
    "Select the cage controller and activate a transform tool":
        "选择笼控制器并启用变换工具",
    "Move": "移动",
    "Move the deformation cage": "移动形变笼",
    "Rotate": "旋转",
    "Rotate and aim the deformation cage": "旋转形变笼并确定朝向",
    "Scale": "缩放",
    "Resize the deformation cage": "调整形变笼尺寸",
    "Show Cage": "显示笼",
    "Draw the cyan cage and orange deformation guide": "显示青色笼和橙色形变引导线",
    "Show Axis Switch": "显示轴向切换",
    "Show bend-trend choices around the cage; the choices hide after selection unless Ctrl is held":
        "在笼体周围显示弯曲趋势选项；选择后自动隐藏，按住 Ctrl 可保持显示",
    "Show Bend Direction Handle": "显示弯曲方向手柄",
    "Show a separate ring for adjusting the Bend direction":
        "显示用于调整弯曲方向的独立圆环",
    "Axis Switch": "轴向切换",
    "Direction Ring": "方向圆环",
    "Bend Trend": "弯曲趋势",
    "Fine Direction": "精细方向",
    "Helper objects stay hidden until cage transform":
        "辅助物体默认隐藏，仅在变换笼时显示",
    "Numeric Controls": "数值控制",
    "Show exact cage size, location, and rotation values":
        "显示精确的笼尺寸、位置和旋转数值",
    "Independent Ends": "独立端部",
    "Show separate top and bottom cross-section controls":
        "显示顶部和底部的独立横截面控制",
    "Top Scale": "顶部缩放",
    "Scale the top cage cross-section without changing the bottom":
        "只缩放笼的顶部横截面，不改变底部",
    "Bottom Scale": "底部缩放",
    "Scale the bottom cage cross-section without changing the top":
        "只缩放笼的底部横截面，不改变顶部",
    "Top Offset": "顶部偏移",
    "Move the top cage cross-section without changing the bottom":
        "只移动笼的顶部横截面，不改变底部",
    "Bottom Offset": "底部偏移",
    "Move the bottom cage cross-section without changing the top":
        "只移动笼的底部横截面，不改变顶部",
    "Offset": "偏移",
    "Show Shape Handles": "显示端面塑形手柄",
    "Show separate top and bottom cross-section shaping handles":
        "显示顶部和底部的独立横截面塑形手柄",
    "Show Length Handles": "显示长度手柄",
    "Show handles that move the top or bottom cage boundary independently":
        "显示可独立移动笼顶部或底部边界的手柄",
    "Limit to Object Bounds": "限制在物体边界内",
    "Prevent the top and bottom cage boundaries from moving beyond the input object's bounds":
        "防止顶部和底部笼边界超出输入物体的边界",
    "Length handles stop at the object bounds":
        "长度手柄不会越过物体边界",
    "Outer length handles stop at the object bounds":
        "首尾长度手柄不会越过物体边界",
    "Reset Independent Ends": "重置独立端部",
    "Restore both cage ends to the fitted cross-section":
        "将笼的两个端部恢复为适配时的横截面",
    "Cyan top / green bottom: drag one end only":
        "青色顶部 / 绿色底部：仅拖动一个端部",
    "Top End Shape": "顶部端面形态",
    "Bottom End Shape": "底部端面形态",
    "Yellow top / amber bottom: move one boundary":
        "黄色顶部 / 琥珀色底部：仅移动一个边界",
    "Top Boundary": "顶部边界",
    "Bottom Boundary": "底部边界",
    "Shared Boundary": "共享边界",
    "Cage Length": "笼长度",
    "Interior boundaries resize both neighboring cages":
        "内部边界会联动调整相邻两个笼的长度",
    "Interior boundaries adjust cage length and gap without overlap":
        "内部边界会调整笼长度和间隔，并避免相互交叉",
    "Drag Along Cage • Shift Precise • Ctrl Snap":
        "沿笼方向拖动 • Shift 精细调整 • Ctrl 吸附",
    "Alt Slide X • Shift Precise • Ctrl Snap":
        "Alt 沿 X 移动 • Shift 精细调整 • Ctrl 吸附",
    "Location": "位置",
    "Rotation": "旋转",
    "Orange handle: drag Angle": "橙色手柄：拖动角度",
    "Orange handle: drag Factor": "橙色手柄：拖动系数",
    "Alt Direction • Shift Precise • Ctrl Snap":
        "Alt 调整方向 • Shift 精细调整 • Ctrl 吸附",
    "Shift Precise • Ctrl Snap": "Shift 精细调整 • Ctrl 吸附",
    "Drag Around Ring • Shift Precise • Ctrl Snap":
        "环绕圆环拖动 • Shift 精细调整 • Ctrl 吸附",
    "Drag Along Axis • Shift Precise • Ctrl Snap":
        "沿轴向拖动 • Shift 精细调整 • Ctrl 吸附",
    "Bend Direction": "弯曲方向",
    "Set Bend Trend": "设置弯曲趋势",
    "Choose Bend Trend": "选择弯曲趋势",
    "Choose a signed cage axis and one of its two perpendicular bend trends; hold Ctrl to keep all choices visible":
        "选择笼的正负轴向及对应的两种正交弯曲趋势；按住 Ctrl 可保持全部选项显示",
    "Switch Cage Axis": "切换笼轴向",
    "Axis switch: RGB is X/Y/Z; diamond is +, ring is -":
        "轴向切换：RGB 对应 X/Y/Z；菱形为正向，圆环为负向",
    "Orange double arrow: drag Bend angle":
        "橙色双向箭头：拖动弯曲角度",
    "Small orange double arrow: drag Bend direction":
        "小型橙色双向箭头：拖动弯曲方向",
    "Large purple twist arc: drag around its center":
        "大型紫色扭转弧：围绕中心拖动",
    "Red / green arrows: horizontal / vertical bend trend":
        "红色 / 绿色箭头：横向 / 竖向弯曲趋势",
    "Click to choose and close • Ctrl keeps choices open":
        "点击选择并收起 • 按住 Ctrl 保持选项显示",
    "Amber taper handle: drag Factor": "琥珀色锥化手柄：拖动系数",
    "Green stretch handle: drag Factor": "绿色拉伸手柄：拖动系数",
    "Set Deform Axis": "设置形变轴",
    "Align the cage axis and fit it to the current stage input":
        "对齐笼轴线并适配当前阶段输入",
    "Show Toggle Bend Axis Gizmo": "显示切换弯曲轴向Gizmo",
    "AIGODLIKE Community:小萌新": "AIGODLIKE社区,小萌新",
    "AIGODLIKE": "辣椒出品",
    "Gizmo Property Show Location": "Gizmo属性显示位置",
    "You can press the following shortcut keys when dragging values":
        "拖动值时可以按以下快捷键",
    "    Wheel:   Switch Origin Ctrl Mode":
        "    滚轮:   切换原点控制模式",
    "    X,Y,Z:  Switch Modifier Deform Axis":
        "    X,Y,Z:  切换修改器型变轴",
    "    W:       Switch Deform Wireframe Show":
        "    W:       切换形变线框显示",

    "    A:       Switch To Select Bend Axis Mode(deform_method=='BEND')":
        "    A:       切换到选择弯曲轴模式(形变方法='弯曲')",
    "Show Set Axis Button": "显示设置轴向Gizmo",
    "Follow Upper Limit(Red)": "跟随上限(红色)",
    "Follow Lower Limit(Green)": "跟随下限(绿色)",
    "Lower limit(Green)": "下限(绿色)",
    "UP Limits(Red)": "上限(红色)",
    "Show Deform Wireframe": "显示形变线框",

    "Minimum value between upper and lower limits": "上限与下限之间的最小值",
    "Upper and lower limit tolerance": "上下限容差",

    "Draw Upper and lower limit Bound Box Color": "绘制网格上限下限边界线框的颜色",
    "Upper and lower limit Bound Box Color": "上限下限边界框颜色",
    "Draw Bound Box Color": "绘制网格边界框的颜色",
    "Bound Box": "边界框颜色",
    "Draw Deform Wireframe Color": "绘制网格形变形状线框的颜色",
    "Deform Wireframe": "形变线框颜色",

    "Simple Deform visualization adjustment tool": "简易形变可视化工具",

    "Select an object and the active modifier is Simple Deform":
        "选择物体并且活动修改器为简易形变",
    "Bound Middle": "边界框中心",
    origin_text(not_add, "as the lower limit"):
        "添加一个空物体原点作为旋转轴(如果已有原点则不添加),并在操作时设置原点位置为下限位置",
    origin_text(not_add, "as the upper limit"):
        "添加一个空物体原点作为旋转轴(如果已有原点则不添加),并在操作时设置原点位置为上限位置",
    origin_text("it will not be added",
                "between the upper and lower limits"):
        "添加一个空物体原点作为旋转轴(如果已有原点则不添加),并在操作时设置原点位置为上下限之间的位置",
    origin_text(not_add,
                "as the position between the bounding boxes"):
        "添加一个空物体原点作为旋转轴(如果已有原点则不添加),并在操作时设置原点位置为边界框之间的位置",
    "No origin operation": "不进行原点操作",
    "Origin control mode": "原点控制模式",
    "Down limit": "下限",
    "Coefficient": "系数",
    "Up limit": "上限",
    "Upper limit": "上限",

    "3D View -> Select an object and the active modifier is simple "
    "deformation": "3D视图 -> 选择一个物体,"
                   "并且活动修改器为简易形修改器",

    "3D View: Simple Deform Helper": "3D 视图: Simple Deform Helper 简易形变助手",
    "Simple Deform Helper": "简易形变助手",
    "Tool Options": "工具选项",
    "The scaling value of the object is not 1": "对象的缩放值不是1",

    "which will cause the deformation of the simple deformation "
    "modifier.": "这将导致简易形变修改器变形",
    "Please apply the scaling before deformation.": "请应用缩放",
    "Z Rotate": "Z扭转",
    "Simple Deform Animated": "简易形变动画",
    "Simple Deform Property": "简易形变属性",
    "Insert Keyframe": "插入关键帧",
    "Remove Keyframe": "删除关键帧",
    "Show Simple Deform Gizmo": "显示简易形变 Gizmo",
    "Simple Deform Stack": "简易形变堆栈",
    "Show Other Simple Deform Stages": "显示其它简易形变阶段",
    "Draw faint input bounds for other Simple Deform modifiers":
        "绘制其它简易形变修改器的低透明度输入边界",
    "Show Drag Shortcuts in Header": "在顶部显示拖动快捷键",
    "Warn About Low Topology": "低拓扑警告",
    "Warn when the active deformation axis has too few geometry points":
        "活动形变轴上的几何点过少时显示警告",
    "Wireframe Preview FPS": "线框预览帧率",
    "Maximum refresh rate for the optional deformed wireframe preview":
        "可选形变线框预览的最高刷新率",
    "User Origin is protected": "用户 Origin 已受保护",
    "Follow-limit Origin modes are disabled.": "已禁用跟随限制的 Origin 模式。",
    "Simple Deform needs more segments to bend smoothly.":
        "简易形变需要更多分段才能平滑弯曲。",
    "Add Subdivision Before Deform": "在形变前添加细分",
    "Add a non-destructive subdivision modifier before the active Simple Deform":
        "在活动简易形变之前添加非破坏性细分修改器",
    "Switch Simple Deform Stage": "切换简易形变阶段",
    "Make the previous or next Simple Deform modifier active":
        "将上一个或下一个简易形变修改器设为活动项"
}


def _localized_catalog(overrides):
    """Use English source text for untranslated long-tail entries."""
    catalog = {source: source for source in translations_dict}
    catalog.update(overrides)
    return catalog


translations_ja_JP = _localized_catalog({
    "Rotation Mode": "回転モード",
    "Previous": "前へ",
    "Next": "次へ",
    "Select the previous Simple Deform modifier": "前の Simple Deform 修正子を選択",
    "Select the next Simple Deform modifier": "次の Simple Deform 修正子を選択",
    "Earlier": "前に移動",
    "Later": "後に移動",
    "Tool Settings": "ツール設定",
    "In Front": "前面に表示",
    "Show Gizmo": "ギズモを表示",
    "Stage Index": "ステージ番号",
    "Active Deformation Layer": "アクティブな変形レイヤー",
    "Muted Deformations": "ミュートされた変形",
    "Original Origin": "元の原点",
    "Origin Object Rotate Angle": "原点オブジェクトの回転角度",
    "Origin Object Rotate Axis": "原点オブジェクトの回転軸",
    "Expand every deformation layer in the cage UI": "ケージ UI ですべての変形レイヤーを展開",
    "Persistent execution order for the enabled deformation layers": "有効な変形レイヤーの実行順を保持",
    "Index of the deformation layer selected in the cage UI": "ケージ UI で選択中の変形レイヤーのインデックス",
    "Present deformation layers temporarily bypassed by this cage": "このケージが一時的にバイパスしている既存の変形レイヤー",
    "Temporarily bypass Bend": "曲げを一時的にバイパス",
    "Temporarily bypass Twist": "ねじりを一時的にバイパス",
    "Temporarily bypass Taper": "テーパーを一時的にバイパス",
    "Temporarily bypass Stretch": "伸縮を一時的にバイパス",
    "Move before the previous Cage Deform": "前のケージ変形の前へ移動",
    "Move after the next Cage Deform": "次のケージ変形の後へ移動",
    "Key the active strength, limits, and managed Origin controls": "アクティブな強度・制限・管理原点のコントロールにキーを挿入",
    "Remove the current-frame keys created for the active Simple Deform": "アクティブな Simple Deform 用に作成した現在フレームのキーを削除",
    "Create a managed Origin and keep it at the upper limit while dragging": "管理原点を作成し、ドラッグ中は上限に固定",
    "Create a managed Origin and keep it at the lower limit while dragging": "管理原点を作成し、ドラッグ中は下限に固定",
    "Create a managed Origin between the upper and lower limits": "上限と下限の間に管理原点を作成",
    "Create a managed Origin at the deformation bounds center": "変形境界の中央に管理原点を作成",
    "Middle": "中央",
    "Stage {stage_index} of {stage_count}: {modifier}": "ステージ {stage_index}/{stage_count}: {modifier}",
    "Deform {stage_index}/{stage_count}": "変形 {stage_index}/{stage_count}",
    "Low topology on {axis}: {sample_count} levels": "{axis} 軸のトポロジーが低い: {sample_count} レベル",
    "Animated": "アニメーション",
    "Property": "プロパティ",
    "01 Local Space": "01 ローカル空間",
    "02 Cage Profile": "02 ケージプロファイル",
    "07 Mode and Output": "07 モードと出力",
    "Subdivide to Chained Cages": "チェーンケージへ細分化",
    "Split the active cage inside its current range and distribute its deformation across a chained cage stack": "現在の範囲内でアクティブケージを分割し、変形をチェーンケージスタックへ分配",
    "Number of chained segments inside the current cage range": "現在のケージ範囲内のチェーンセグメント数",
    "Uniform spacing between segments; segment lengths shrink so the original total range is preserved": "セグメント間隔を均一にします。元の総範囲を保つため、各セグメントの長さは短縮されます",
    "Keep each newly-created shared cross-section continuous": "新しく作成する共有断面を連続のまま保つ",
    "The original cage boundaries stay fixed.": "元のケージ境界は固定されたままです。",
    "Bend and Twist angles are distributed across segments.": "曲げとねじりの角度は各セグメントへ分配されます。",
    "Batch Edit": "一括編集",
    "Batch Edit Chain": "チェーンを一括編集",
    "Edit several cages in the active chain as one operation": "アクティブチェーン内の複数ケージを一度に編集",
    "Scope": "範囲",
    "Whole Chain": "チェーン全体",
    "Edit every cage in this chain": "このチェーン内のすべてのケージを編集",
    "Start to Active": "始点からアクティブまで",
    "Edit the chain root through the active cage": "チェーンのルートからアクティブケージまでを編集",
    "Active to End": "アクティブから末端まで",
    "Edit the active cage through the chain tip": "アクティブケージからチェーン末端までを編集",
    "Operation": "操作",
    "End Scale": "端部スケール",
    "Batch-edit top and bottom cross-section scale": "上下断面のスケールを一括編集",
    "End Offset": "端部オフセット",
    "Batch-edit top and bottom cross-section offset": "上下断面のオフセットを一括編集",
    "Set spacing before every cage in scope": "範囲内の各ケージ手前の間隔を設定",
    "Batch-edit one deformation parameter": "変形パラメータを 1 つ一括編集",
    "Deformation": "変形",
    "Stage Visibility": "ステージの表示状態",
    "Apply or bypass every cage in scope": "範囲内の各ケージを適用またはバイパス",
    "Ends": "端部",
    "Edit top ends": "上端部を編集",
    "Edit bottom ends": "下端部を編集",
    "Both": "両端",
    "Edit both ends": "両端を同時に編集",
    "Apply As": "適用方法",
    "Set Values": "値を設定",
    "Replace existing values": "既存の値を置き換え",
    "Add Values": "値を加算",
    "Add to existing values": "既存の値に加算",
    "Multiply Values": "値を乗算",
    "Multiply existing values": "既存の値に乗算",
    "X and Z cross-section values": "断面の X と Z の値",
    "X and Z cross-section offset values": "断面の X と Z のオフセット値",
    "Spacing before each affected downstream cage": "影響を受ける下流ケージ手前の間隔",
    "Preserve Total Range": "総範囲を保持",
    "Shorten each cage as its incoming gap grows": "手前の間隔が増えるにつれて各ケージを短縮",
    "Parameter": "パラメータ",
    "Batch-edit Bend angle": "曲げ角度を一括編集",
    "Batch-edit Bend direction": "曲げ方向を一括編集",
    "Batch-edit Twist angle": "ねじり角度を一括編集",
    "Batch-edit Taper factor": "テーパー係数を一括編集",
    "Batch-edit Stretch factor": "伸縮係数を一括編集",
    "Enable Stages": "ステージを有効化",
    "Apply the affected cage stages": "対象のケージステージを適用",
    "Linked shared boundaries are changed only once.": "連動している共有境界は一度だけ変更されます。",
    "Cages without this deformation layer are skipped.": "この変形レイヤーを持たないケージはスキップされます。",
    "Created {count} cage stages": "{count} 個のケージステージを作成しました",
    "Could not create cage chain: {error}": "ケージチェーンを作成できませんでした: {error}",
    "Only a single cage can be subdivided": "細分化できるのは単一ケージのみです",
    "Set the cage origin to Bottom before subdividing": "細分化の前にケージの原点を下部に設定してください",
    "Animated cage parameters cannot be subdivided safely": "アニメーション付きケージパラメータは安全に細分化できません",
    "Taper collapses at an interior split boundary": "テーパーは内側の分割境界で潰れてしまいます",
    "Subdivided cage into {count} chained stages": "ケージを {count} 個のチェーンステージへ細分化しました",
    "Subdivided cage into {count} chained stages (gap clamped to preserve range)": "ケージを {count} 個のチェーンステージへ細分化しました（範囲維持のため間隔を制限）",
    "Could not subdivide cage: {error}": "ケージを細分化できませんでした: {error}",
    "Could not batch edit chain: {error}": "チェーンを一括編集できませんでした: {error}",
    "No matching cage values were changed": "一致するケージ値が変更されませんでした",
    "Updated {count} cage stages": "{count} 個のケージステージを更新しました",
    "Fitted {count} cage stages to chain input": "{count} 個のケージステージをチェーン入力に合わせました",
    "No cage chain metadata was found": "ケージチェーンのメタデータが見つかりません",
    "Missing cage stages: {indices}": "不足しているケージステージ: {indices}",
    "Duplicate cage stage indices: {indices}": "重複しているケージステージ番号: {indices}",
    "A non-cage modifier is inserted inside the chain": "チェーン内にケージ以外の修正子が挿入されています",
    "A chain stage has no matching controller": "チェーンステージに対応するコントローラーがありません",
    "Chain stages use different connection modes": "チェーンステージの接続モードが一致しません",
    "Cage chain is broken": "ケージチェーンが切れています",
    "No Cage Chain was found": "ケージチェーンが見つかりません",
    "Reconnected {count} cage stages": "{count} 個のケージステージを再接続しました",
    "Add Cage Chain": "ケージチェーンを追加",
    "Number of segments to create": "作成するセグメント数",
    "Connection Mode": "接続モード",
    "How neighboring cage segments handle their boundaries": "隣接ケージセグメントが境界をどう扱うか",
    "Continue from each preceding cage": "直前のケージから連続して続ける",
    "Limit each segment to its own box": "各セグメントを自身のボックス内に制限",
    "Gap": "間隔",
    "Gap Before": "手前の間隔",
    "Gap from Previous Cage": "前のケージからの間隔",
    "Non-negative distance from the previous cage; changing it keeps the overall chain span when possible": "前のケージからの非負距離。変更時は可能な限りチェーン全体のスパンを維持します",
    "Distance between this cage and the previous cage": "このケージと前のケージの距離",
    "Distance between neighboring cage frames in target units": "隣接ケージフレーム間の距離（ターゲット単位）",
    "Cage Axis": "ケージ軸",
    "Use the longest input dimension": "入力の最長寸法を使用",
    "Align cage Y to target +X": "ケージ Y をターゲット +X に揃える",
    "Align cage Y to target -X": "ケージ Y をターゲット -X に揃える",
    "Align cage Y to target +Y": "ケージ Y をターゲット +Y に揃える",
    "Align cage Y to target -Y": "ケージ Y をターゲット -Y に揃える",
    "Align cage Y to target +Z": "ケージ Y をターゲット +Z に揃える",
    "Align cage Y to target -Z": "ケージ Y をターゲット -Z に揃える",
    "Select a supported target object first": "まず対応するターゲットオブジェクトを選択してください",
    "Add Simple Deform": "Simple Deform を追加",
    "Add Simple Deform (Legacy)": "Simple Deform を追加（従来）",
    "Add a traditional Simple Deform modifier": "従来の Simple Deform 修正子を追加",
    "Added legacy Simple Deform modifier": "従来の Simple Deform 修正子を追加しました",
    "Cage deformation is not supported for lattice objects": "ラティスオブジェクトではケージ変形に対応していません",
    "The selected surface could not be converted for cage deformation": "選択したサーフェスをケージ変形用に変換できませんでした",
    "Surface cage deformation requires a mesh conversion": "サーフェスのケージ変形にはメッシュへの変換が必要です",
    "Add Chained Cages": "チェーンケージを追加",
    "Create Cage Chain": "ケージチェーンを作成",
    "Create several related deformation cages in one operation": "関連する複数の変形ケージを一度に作成",
    "Cage Count": "ケージ数",
    "Use isolated boxes": "各ボックス内のジオメトリのみに影響",
    "Number of chained cages to create": "作成するチェーンケージ数",
    "Connect Ends": "端部を接続",
    "Align each cage bottom to the previous cage top": "各ケージの下端を前のケージの上端に揃える",
    "Chain Mode": "チェーンモード",
    "Use forward continuation when available": "可能な場合は前方への連続を使用",
    "Create stages without automatic reconnection": "自動再接続なしでステージを作成",
    "Chained": "チェーン",
    "Independent": "独立",
    "Segment": "セグメント",
    "Enable Stage": "ステージを有効化",
    "Temporarily apply or bypass this cage while preserving chained-stage flow": "チェーンステージの流れを保ったまま、このケージを一時的に適用またはバイパス",
    "Show Other Cages": "他のケージを表示",
    "Display inactive cages and make their viewport controls directly editable": "非アクティブケージを表示し、ビューポートコントロールを直接編集可能にする",
    "Show Other Cage Controllers": "他のケージコントローラーを表示",
    "Display all cage controllers except active one": "アクティブ以外のすべてのケージコントローラーを表示",
    "Active Cage": "アクティブケージ",
    "Inactive Cage": "非アクティブケージ",
    "Active cage is highlighted; other cages are dimmed": "アクティブケージは強調表示され、他のケージは暗くなります",
    "Select this cage stage and its controller": "このケージステージとそのコントローラーを選択",
    "Select Cage Stage": "ケージステージを選択",
    "Cage Deform Strength Handle": "ケージ変形の強度ハンドル",
    "Cage End Shape": "ケージ端部の形状",
    "Cage Boundary": "ケージ境界",
    "Auto Reconnect Chain": "チェーンを自動再接続",
    "Automatically refresh downstream cage frames after a chain parameter or controller transform changes": "チェーンパラメータやコントローラーのトランスフォーム変更後、下流のケージフレームを自動更新",
    "Auto Reconnect": "自動再接続",
    "Refresh downstream cage frames after upstream edits": "上流の編集後に下流ケージフレームを更新",
    "Use one-sided continuation": "片側連続を使用",
    "Propagate each preceding cage output frame to the next cage": "直前ケージの出力フレームを次のケージへ伝播",
    "Reconnect Broken Chain": "切れたチェーンを再接続",
    "Attempt contiguous stages even when a stack issue is detected": "スタックの問題が検出されても連続ステージを試行",
    "Cage Deform core is unavailable": "ケージ変形コアを利用できません",
    "Chained Cages": "チェーンケージ",
    "Independent Cage Chain": "独立ケージチェーン",
    "Reconnect Chain": "チェーンを再接続",
    "Reconnect Cage Chain": "ケージチェーンを再接続",
    "Align each cage to the previous cage's output frame": "各ケージを前のケージの出力フレームに揃える",
    "Each stage keeps its own angle and length; reconnect updates the incoming frame.": "各ステージは自身の角度と長さを保持します。再接続は入力フレームのみ更新します。",
    "Each stage keeps its deformations, length, and incoming gap.": "各ステージは自身の変形・長さ・手前の間隔を保持します。",
    "Sync Shared End Scale": "共有端部スケールを同期",
    "Scale both sides of each shared cage seam together while keeping each outer end independent": "各共有ケージ継ぎ目の両側スケールを同期し、外側端部はそれぞれ独立のままにする",
    "Scale both sides of each shared cage seam together while keeping outer ends independent": "各共有ケージ継ぎ目の両側スケールを同期し、外側端部は独立のままにする",
    "Only neighboring seam-end scales are synchronized.": "隣接する継ぎ目端部のスケールのみが同期されます。",
    "Outer cage ends remain independent.": "外側のケージ端部は独立したままです。",
    "Chained mode starts at the lower cage boundary.": "チェーンモードはケージ下端境界から開始します。",
    "Cage Chain mode is locked to Chained.": "ケージチェーンモードはチェーンに固定されています。",
    "Keep the prefix unchanged and continue from the cage end": "前段は変えず、ケージ末端の傾向から継続",
    "Simple Deformer": "シンプル変形器",
    "Simple Deformer V2": "シンプル変形器 V2",
    "Add New Cages to End": "新規ケージをスタック末尾へ追加",
    "Place newly-created cage stages at the end of the modifier stack": "新規ケージステージを修正子スタックの末尾に配置",
    "Cage Deform": "ケージ変形",
    "Add Cage Deform": "ケージ変形を追加",
    "Add an independent cage deformation stage": "独立したケージ変形ステージを追加",
    "Added Cage Deform stage": "ケージ変形ステージを追加しました",
    "Deform axis changed; the user-supplied Origin was preserved": "変形軸を変更しました。ユーザー指定の原点は保持されています",
    "Subdivision was added at the end; move it before Simple Deform": "細分化が末尾に追加されました。Simple Deform の前へ移動してください",
    "Inserted {inserted} Simple Deform keyframe channels": "{inserted} 個の Simple Deform キーフレームチャンネルを挿入しました",
    "Removed {removed} Simple Deform keyframe channels": "{removed} 個の Simple Deform キーフレームチャンネルを削除しました",
    "Independent cage deformation": "独立ケージ変形",
    "Bend, Twist, Taper, and Stretch.": "曲げ、ねじり、テーパー、伸縮に対応。",
    "Combine Bend, Twist, Taper, and Stretch in one cage.": "1 つのケージで曲げ・ねじり・テーパー・伸縮を組み合わせられます。",
    "Cage Stack": "ケージスタック",
    "Move Cage Stage": "ケージステージを移動",
    "Move this deformation earlier or later in the modifier stack": "修正子スタック内でこの変形を前後に移動",
    "Duplicate Cage Stage": "ケージステージを複製",
    "Duplicate": "複製",
    "Remove Cage Stage": "ケージステージを削除",
    "Remove Stage": "ステージを削除",
    "Remove Cage Stack": "ケージスタックを削除",
    "Remove": "削除",
    "Remove this managed deformation stage and its cage controller": "この管理変形ステージとそのケージコントローラーを削除",
    "Remove every managed cage stage and its owned controllers": "すべての管理ケージステージと所有コントローラーを削除",
    "Shape": "形状",
    "Deformation Layers": "変形レイヤー",
    "Expand All": "すべて展開",
    "Add Deformation": "変形を追加",
    "Add Deformation Layer": "変形レイヤーを追加",
    "Add one deformation operation to this cage": "このケージに変形操作を 1 つ追加",
    "Select Deformation Layer": "変形レイヤーを選択",
    "Select this deformation layer without changing its evaluation": "評価状態を変えずにこの変形レイヤーを選択",
    "Remove Deformation Layer": "変形レイヤーを削除",
    "Remove this deformation operation from the cage": "このケージから変形操作を削除",
    "Toggle Deformation Layer": "変形レイヤーの有効状態を切替",
    "Temporarily bypass or restore this deformation without losing its settings": "設定を失わずにこの変形を一時バイパスまたは復元",
    "Move Deformation Layer": "変形レイヤーを移動",
    "Move this deformation operation earlier or later": "この変形操作を前後に移動",
    "Up": "上へ",
    "Down": "下へ",
    "Execute this layer earlier": "このレイヤーをより早く実行",
    "Execute this layer later": "このレイヤーをより遅く実行",
    "This deformation is already enabled": "この変形はすでに有効です",
    "Deformation Type": "変形タイプ",
    "Deformation Types": "変形タイプ",
    "Deformations": "変形",
    "Shape operations combined by this cage": "このケージが組み合わせる形状操作",
    "Enable one or more deformation operations in this cage": "このケージで 1 つ以上の変形操作を有効化",
    "At least one deformation type must remain enabled": "少なくとも 1 つの変形タイプを有効のままにする必要があります",
    "Shape operation performed inside the cage": "ケージ内で行う形状操作",
    "Bend": "曲げ",
    "Curve geometry along the cage axis": "ケージ軸に沿ってジオメトリを曲げる",
    "Twist": "ねじり",
    "Rotate cross-sections around the cage axis": "断面をケージ軸まわりに回転",
    "Taper": "テーパー",
    "Scale cross-sections along the cage axis": "ケージ軸に沿って断面をスケール",
    "Stretch": "伸縮",
    "Scale geometry along the cage axis": "ケージ軸に沿ってジオメトリをスケール",
    "Angle": "角度",
    "Total Bend or Twist angle through the cage length": "ケージ全長にわたる曲げまたはねじりの合計角度",
    "Bend Strength": "曲げの強さ",
    "Bend angle through the cage length": "ケージ全長にわたる曲げ角度",
    "Bend Angle": "曲げ角度",
    "Total Bend angle through the cage length": "ケージ全長にわたる曲げの合計角度",
    "Twist Strength": "ねじりの強さ",
    "Twist angle through the cage length": "ケージ全長にわたるねじり角度",
    "Twist Angle": "ねじり角度",
    "Total Twist angle through the cage length": "ケージ全長にわたるねじりの合計角度",
    "Taper Factor": "テーパー係数",
    "Amount of taper along the cage axis": "ケージ軸に沿ったテーパー量",
    "Cross-section scale change through the cage length": "ケージ全長にわたる断面スケールの変化量",
    "Stretch Factor": "伸縮係数",
    "Amount of stretch along the cage axis": "ケージ軸に沿った伸縮量",
    "Length scale change through the cage": "ケージにわたる長さスケールの変化量",
    "Factor": "係数",
    "Amount used by Taper and Stretch": "テーパーと伸縮で使う量",
    "Direction": "方向",
    "Direction of Bend around the cage axis": "ケージ軸まわりの曲げ方向",
    "Mode": "モード",
    "How geometry outside the cage is handled": "ケージ外ジオメトリの扱い方",
    "Limited": "制限",
    "Deform inside; continue outside from the cage ends": "内側を変形し、外側はケージ端部から継続",
    "Within Box": "ボックス内",
    "Only points inside the cage are affected": "ケージ内の点のみ影響を受けます",
    "Unlimited": "無制限",
    "Continue deformation beyond the cage": "ケージを超えて変形を継続",
    "Origin": "原点",
    "Starting pattern of the deformation": "変形の開始パターン",
    "Bottom": "下部",
    "Start at the lower cage boundary": "ケージ下端境界から開始",
    "Center": "中心",
    "Use signed distance from the cage center": "ケージ中心からの符号付き距離を使用",
    "Symmetric": "対称",
    "Mirror the deformation profile across the center": "変形プロファイルを中心でミラー",
    "Top": "上部",
    "Start at the upper cage boundary": "ケージ上端境界から開始",
    "Preserve Volume": "体積を維持",
    "Compensate cross-section size while stretching": "伸縮時に断面サイズを補正",
    "Cage Controls": "ケージコントロール",
    "Deform Axis": "変形軸",
    "Target axis used when aligning and fitting the cage": "ケージの整列とフィットに使うターゲット軸",
    "Size": "サイズ",
    "Dimensions of the independent deformation cage": "独立変形ケージの寸法",
    "Auto": "自動",
    "Use the longest local dimension": "最長のローカル寸法を使用",
    "Align & Fit": "整列してフィット",
    "Align & Fit Chain": "チェーンを整列してフィット",
    "Fit to Object": "オブジェクトに合わせる",
    "Fit the active cage, or its entire connected chain, to the geometry entering the deformation": "アクティブケージ、または接続されたチェーン全体を、変形へ入るジオメトリに合わせる",
    "Select Cage": "ケージを選択",
    "Select Cage Controller": "ケージコントローラーを選択",
    "Return to Object": "オブジェクトに戻る",
    "Select the object controlled by this deformation cage": "この変形ケージが制御するオブジェクトを選択",
    "Edit Cage": "ケージを編集",
    "Select the cage controller and activate a transform tool": "ケージコントローラーを選択し、トランスフォームツールを有効化",
    "Move": "移動",
    "Move the deformation cage": "変形ケージを移動",
    "Rotate": "回転",
    "Rotate and aim the deformation cage": "変形ケージを回転して向きを決める",
    "Scale": "スケール",
    "Resize the deformation cage": "変形ケージのサイズを変更",
    "Show Cage": "ケージを表示",
    "Draw the cyan cage and orange deformation guide": "シアンのケージとオレンジの変形ガイドを描画",
    "Show Axis Switch": "軸切替を表示",
    "Show bend-trend choices around the cage; the choices hide after selection unless Ctrl is held": "ケージ周囲に曲げ傾向の選択肢を表示。選択後は隠れますが、Ctrl を押している間は表示を維持",
    "Show Bend Direction Handle": "曲げ方向ハンドルを表示",
    "Show a separate ring for adjusting the Bend direction": "曲げ方向調整用の独立リングを表示",
    "Axis Switch": "軸切替",
    "Direction Ring": "方向リング",
    "Bend Trend": "曲げ傾向",
    "Fine Direction": "精密方向",
    "Helper objects stay hidden until cage transform": "ヘルパーオブジェクトはケージ変形時まで非表示",
    "Numeric Controls": "数値コントロール",
    "Show exact cage size, location, and rotation values": "ケージの正確なサイズ・位置・回転値を表示",
    "Independent Ends": "独立端部",
    "Show separate top and bottom cross-section controls": "上下断面の個別コントロールを表示",
    "Top Scale": "上部スケール",
    "Scale the top cage cross-section without changing the bottom": "下部を変えずに上部ケージ断面のみスケール",
    "Bottom Scale": "下部スケール",
    "Scale the bottom cage cross-section without changing the top": "上部を変えずに下部ケージ断面のみスケール",
    "Top Offset": "上部オフセット",
    "Move the top cage cross-section without changing the bottom": "下部を変えずに上部ケージ断面のみ移動",
    "Bottom Offset": "下部オフセット",
    "Move the bottom cage cross-section without changing the top": "上部を変えずに下部ケージ断面のみ移動",
    "Offset": "オフセット",
    "Show Shape Handles": "形状ハンドルを表示",
    "Show separate top and bottom cross-section shaping handles": "上下断面の個別整形ハンドルを表示",
    "Show Length Handles": "長さハンドルを表示",
    "Show handles that move the top or bottom cage boundary independently": "上下ケージ境界を個別に動かすハンドルを表示",
    "Limit to Object Bounds": "オブジェクト境界内に制限",
    "Prevent the top and bottom cage boundaries from moving beyond the input object's bounds": "上下ケージ境界が入力オブジェクトの境界を超えないようにする",
    "Length handles stop at the object bounds": "長さハンドルはオブジェクト境界で止まります",
    "Outer length handles stop at the object bounds": "外側の長さハンドルはオブジェクト境界で止まります",
    "Reset Independent Ends": "独立端部をリセット",
    "Restore both cage ends to the fitted cross-section": "両ケージ端部をフィット時の断面へ戻す",
    "Cyan top / green bottom: drag one end only": "シアン上部 / 緑下部: 片方の端部のみドラッグ",
    "Top End Shape": "上端部の形状",
    "Bottom End Shape": "下端部の形状",
    "Yellow top / amber bottom: move one boundary": "黄上部 / 琥珀下部: 片方の境界のみ移動",
    "Top Boundary": "上境界",
    "Bottom Boundary": "下境界",
    "Shared Boundary": "共有境界",
    "Cage Length": "ケージ長さ",
    "Interior boundaries resize both neighboring cages": "内側境界は隣接する両ケージの長さを同時に変更します",
    "Interior boundaries adjust cage length and gap without overlap": "内側境界は重ならないようケージ長さと間隔を調整します",
    "Drag Along Cage • Shift Precise • Ctrl Snap": "ケージに沿ってドラッグ • Shift 精密 • Ctrl スナップ",
    "Alt Slide X • Shift Precise • Ctrl Snap": "Alt で X スライド • Shift 精密 • Ctrl スナップ",
    "Location": "位置",
    "Rotation": "回転",
    "Orange handle: drag Angle": "オレンジハンドル: 角度をドラッグ",
    "Orange handle: drag Factor": "オレンジハンドル: 係数をドラッグ",
    "Alt Direction • Shift Precise • Ctrl Snap": "Alt で方向 • Shift 精密 • Ctrl スナップ",
    "Shift Precise • Ctrl Snap": "Shift 精密 • Ctrl スナップ",
    "Drag Around Ring • Shift Precise • Ctrl Snap": "リング周囲をドラッグ • Shift 精密 • Ctrl スナップ",
    "Drag Along Axis • Shift Precise • Ctrl Snap": "軸に沿ってドラッグ • Shift 精密 • Ctrl スナップ",
    "Bend Direction": "曲げ方向",
    "Set Bend Trend": "曲げ傾向を設定",
    "Choose Bend Trend": "曲げ傾向を選択",
    "Choose a signed cage axis and one of its two perpendicular bend trends; hold Ctrl to keep all choices visible": "符号付きケージ軸とその直交する 2 つの曲げ傾向から選択。Ctrl を押すと選択肢を表示したままにできます",
    "Switch Cage Axis": "ケージ軸を切替",
    "Axis switch: RGB is X/Y/Z; diamond is +, ring is -": "軸切替: RGB は X/Y/Z、菱形は +、リングは -",
    "Orange double arrow: drag Bend angle": "オレンジの双方向矢印: 曲げ角度をドラッグ",
    "Small orange double arrow: drag Bend direction": "小さなオレンジ双方向矢印: 曲げ方向をドラッグ",
    "Large purple twist arc: drag around its center": "大きな紫のねじり弧: 中心まわりにドラッグ",
    "Red / green arrows: horizontal / vertical bend trend": "赤 / 緑の矢印: 水平 / 垂直の曲げ傾向",
    "Click to choose and close • Ctrl keeps choices open": "クリックで選択して閉じる • Ctrl で選択肢を開いたまま",
    "Amber taper handle: drag Factor": "琥珀のテーパーハンドル: 係数をドラッグ",
    "Green stretch handle: drag Factor": "緑の伸縮ハンドル: 係数をドラッグ",
    "Set Deform Axis": "変形軸を設定",
    "Align the cage axis and fit it to the current stage input": "ケージ軸を揃え、現在のステージ入力にフィット",
    "Show Toggle Bend Axis Gizmo": "曲げ軸切替ギズモを表示",
    "AIGODLIKE Community:小萌新": "AIGODLIKE Community: 小萌新",
    "AIGODLIKE": "AIGODLIKE",
    "Gizmo Property Show Location": "ギズモプロパティの表示位置",
    "You can press the following shortcut keys when dragging values": "値のドラッグ中に次のショートカットを使用できます",
    "    Wheel:   Switch Origin Ctrl Mode": "    Wheel:   原点 Ctrl モードを切替",
    "    X,Y,Z:  Switch Modifier Deform Axis": "    X,Y,Z:  修正子の変形軸を切替",
    "    W:       Switch Deform Wireframe Show": "    W:       変形ワイヤーフレーム表示を切替",
    "    A:       Switch To Select Bend Axis Mode(deform_method=='BEND')": "    A:       曲げ軸選択モードへ切替(deform_method=='BEND')",
    "Show Set Axis Button": "軸設定ギズモを表示",
    "Follow Upper Limit(Red)": "上限に追従(赤)",
    "Follow Lower Limit(Green)": "下限に追従(緑)",
    "Lower limit(Green)": "下限(緑)",
    "UP Limits(Red)": "上限(赤)",
    "Show Deform Wireframe": "変形ワイヤーフレームを表示",
    "Minimum value between upper and lower limits": "上限と下限の間の最小値",
    "Upper and lower limit tolerance": "上下限の許容差",
    "Draw Upper and lower limit Bound Box Color": "上下限バウンドボックスの描画色",
    "Upper and lower limit Bound Box Color": "上下限バウンドボックスの色",
    "Draw Bound Box Color": "バウンドボックスの描画色",
    "Bound Box": "バウンドボックス",
    "Draw Deform Wireframe Color": "変形ワイヤーフレームの描画色",
    "Deform Wireframe": "変形ワイヤーフレーム",
    "Simple Deform visualization adjustment tool": "Simple Deform 可視化調整ツール",
    "Select an object and the active modifier is Simple Deform": "オブジェクトを選択し、アクティブ修正子が Simple Deform であること",
    "Bound Middle": "バウンド中央",
    "Add an empty object origin as the rotation axis (if there is an origin, do not add it), and set the origin position as the lower limit during operation": "回転軸として空オブジェクトの原点を追加し（既にあれば追加しない）、操作中は原点位置を下限に設定",
    "Add an empty object origin as the rotation axis (if there is an origin, do not add it), and set the origin position as the upper limit during operation": "回転軸として空オブジェクトの原点を追加し（既にあれば追加しない）、操作中は原点位置を上限に設定",
    "Add an empty object origin as the rotation axis (if there is an origin, it will not be added), and set the origin position between the upper and lower limits during operation": "回転軸として空オブジェクトの原点を追加し（既にあれば追加しない）、操作中は原点位置を上下限の間に設定",
    "Add an empty object origin as the rotation axis (if there is an origin, do not add it), and set the origin position as the position between the bounding boxes during operation": "回転軸として空オブジェクトの原点を追加し（既にあれば追加しない）、操作中は原点位置をバウンドボックス間に設定",
    "No origin operation": "原点操作なし",
    "Origin control mode": "原点コントロールモード",
    "Down limit": "下限",
    "Coefficient": "係数",
    "Up limit": "上限",
    "Upper limit": "上限",
    "3D View -> Select an object and the active modifier is simple deformation": "3Dビュー -> オブジェクトを選択し、アクティブ修正子がシンプル変形であること",
    "3D View: Simple Deform Helper": "3Dビュー: Simple Deform Helper",
    "Simple Deform Helper": "シンプル変形ヘルパー",
    "Tool Options": "ツールオプション",
    "The scaling value of the object is not 1": "オブジェクトのスケール値が 1 ではありません",
    "which will cause the deformation of the simple deformation modifier.": "これによりシンプル変形修正子の変形結果が歪みます。",
    "Please apply the scaling before deformation.": "変形前にスケールを適用してください。",
    "Z Rotate": "Z 回転",
    "Simple Deform Animated": "Simple Deform アニメーション",
    "Simple Deform Property": "Simple Deform プロパティ",
    "Insert Keyframe": "キーフレームを挿入",
    "Remove Keyframe": "キーフレームを削除",
    "Show Simple Deform Gizmo": "Simple Deform ギズモを表示",
    "Simple Deform Stack": "Simple Deform スタック",
    "Show Other Simple Deform Stages": "他の Simple Deform ステージを表示",
    "Draw faint input bounds for other Simple Deform modifiers": "他の Simple Deform 修正子の入力境界を薄く描画",
    "Show Drag Shortcuts in Header": "ヘッダーにドラッグショートカットを表示",
    "Warn About Low Topology": "低トポロジーを警告",
    "Warn when the active deformation axis has too few geometry points": "アクティブ変形軸のジオメトリ点が少なすぎる場合に警告",
    "Wireframe Preview FPS": "ワイヤーフレームプレビュー FPS",
    "Maximum refresh rate for the optional deformed wireframe preview": "任意の変形ワイヤーフレームプレビューの最大更新レート",
    "User Origin is protected": "ユーザー原点は保護されています",
    "Follow-limit Origin modes are disabled.": "制限追従の原点モードは無効です。",
    "Simple Deform needs more segments to bend smoothly.": "Simple Deform を滑らかに曲げるには、さらにセグメントが必要です。",
    "Add Subdivision Before Deform": "変形前に細分化を追加",
    "Add a non-destructive subdivision modifier before the active Simple Deform": "アクティブな Simple Deform の前に非破壊の細分化修正子を追加",
    "Switch Simple Deform Stage": "Simple Deform ステージを切替",
    "Make the previous or next Simple Deform modifier active": "前または次の Simple Deform 修正子をアクティブにする",
})


translations_ko_KR = _localized_catalog({
    "Rotation Mode": "회전 모드",
    "Previous": "이전",
    "Next": "다음",
    "Select the previous Simple Deform modifier": "이전 Simple Deform 수정자 선택",
    "Select the next Simple Deform modifier": "다음 Simple Deform 수정자 선택",
    "Earlier": "앞으로",
    "Later": "뒤로",
    "Tool Settings": "도구 설정",
    "In Front": "앞에 표시",
    "Show Gizmo": "기즈모 표시",
    "Stage Index": "스테이지 인덱스",
    "Active Deformation Layer": "활성 변형 레이어",
    "Muted Deformations": "뮤트된 변형",
    "Original Origin": "원래 원점",
    "Origin Object Rotate Angle": "원점 오브젝트 회전 각도",
    "Origin Object Rotate Axis": "원점 오브젝트 회전 축",
    "Expand every deformation layer in the cage UI": "케이지 UI에서 모든 변형 레이어 펼치기",
    "Persistent execution order for the enabled deformation layers": "활성화된 변형 레이어의 실행 순서 유지",
    "Index of the deformation layer selected in the cage UI": "케이지 UI에서 선택된 변형 레이어 인덱스",
    "Present deformation layers temporarily bypassed by this cage": "이 케이지가 일시적으로 우회하는 기존 변형 레이어",
    "Temporarily bypass Bend": "구부리기 일시 우회",
    "Temporarily bypass Twist": "비틀기 일시 우회",
    "Temporarily bypass Taper": "테이퍼 일시 우회",
    "Temporarily bypass Stretch": "늘리기 일시 우회",
    "Move before the previous Cage Deform": "이전 케이지 변형 앞으로 이동",
    "Move after the next Cage Deform": "다음 케이지 변형 뒤로 이동",
    "Key the active strength, limits, and managed Origin controls": "활성 강도, 제한, 관리 원점 컨트롤에 키 삽입",
    "Remove the current-frame keys created for the active Simple Deform": "활성 Simple Deform용으로 만든 현재 프레임 키 제거",
    "Create a managed Origin and keep it at the upper limit while dragging": "관리 원점을 만들고 드래그 중에는 상한에 유지",
    "Create a managed Origin and keep it at the lower limit while dragging": "관리 원점을 만들고 드래그 중에는 하한에 유지",
    "Create a managed Origin between the upper and lower limits": "상한과 하한 사이에 관리 원점 만들기",
    "Create a managed Origin at the deformation bounds center": "변형 경계 중심에 관리 원점 만들기",
    "Middle": "중간",
    "Stage {stage_index} of {stage_count}: {modifier}": "스테이지 {stage_index}/{stage_count}: {modifier}",
    "Deform {stage_index}/{stage_count}": "변형 {stage_index}/{stage_count}",
    "Low topology on {axis}: {sample_count} levels": "{axis} 축 토폴로지가 낮음: {sample_count} 레벨",
    "Animated": "애니메이션",
    "Property": "속성",
    "01 Local Space": "01 로컬 공간",
    "02 Cage Profile": "02 케이지 프로파일",
    "07 Mode and Output": "07 모드와 출력",
    "Subdivide to Chained Cages": "체인 케이지로 세분",
    "Split the active cage inside its current range and distribute its deformation across a chained cage stack": "현재 범위 안에서 활성 케이지를 분할하고 변형을 체인 케이지 스택에 분배",
    "Number of chained segments inside the current cage range": "현재 케이지 범위 안의 체인 세그먼트 수",
    "Uniform spacing between segments; segment lengths shrink so the original total range is preserved": "세그먼트 간격을 균일하게 유지합니다. 원래 총 범위를 보존하도록 세그먼트 길이가 줄어듭니다",
    "Keep each newly-created shared cross-section continuous": "새로 만든 공유 단면을 연속으로 유지",
    "The original cage boundaries stay fixed.": "원래 케이지 경계는 고정된 채로 유지됩니다.",
    "Bend and Twist angles are distributed across segments.": "구부리기와 비틀기 각도는 각 세그먼트에 분배됩니다.",
    "Batch Edit": "일괄 편집",
    "Batch Edit Chain": "체인 일괄 편집",
    "Edit several cages in the active chain as one operation": "활성 체인의 여러 케이지를 한 번에 편집",
    "Scope": "범위",
    "Whole Chain": "전체 체인",
    "Edit every cage in this chain": "이 체인의 모든 케이지 편집",
    "Start to Active": "시작부터 활성까지",
    "Edit the chain root through the active cage": "체인 루트부터 활성 케이지까지 편집",
    "Active to End": "활성부터 끝까지",
    "Edit the active cage through the chain tip": "활성 케이지부터 체인 끝까지 편집",
    "Operation": "작업",
    "End Scale": "끝단 스케일",
    "Batch-edit top and bottom cross-section scale": "상·하 단면 스케일 일괄 편집",
    "End Offset": "끝단 오프셋",
    "Batch-edit top and bottom cross-section offset": "상·하 단면 오프셋 일괄 편집",
    "Set spacing before every cage in scope": "범위 내 각 케이지 앞 간격 설정",
    "Batch-edit one deformation parameter": "변형 매개변수 하나를 일괄 편집",
    "Deformation": "변형",
    "Stage Visibility": "스테이지 표시 상태",
    "Apply or bypass every cage in scope": "범위 내 각 케이지를 적용하거나 우회",
    "Ends": "끝단",
    "Edit top ends": "상단 편집",
    "Edit bottom ends": "하단 편집",
    "Both": "양쪽",
    "Edit both ends": "양쪽 끝단 동시 편집",
    "Apply As": "적용 방식",
    "Set Values": "값 설정",
    "Replace existing values": "기존 값 바꾸기",
    "Add Values": "값 더하기",
    "Add to existing values": "기존 값에 더하기",
    "Multiply Values": "값 곱하기",
    "Multiply existing values": "기존 값에 곱하기",
    "X and Z cross-section values": "단면 X와 Z 값",
    "X and Z cross-section offset values": "단면 X와 Z 오프셋 값",
    "Spacing before each affected downstream cage": "영향받는 각 하류 케이지 앞 간격",
    "Preserve Total Range": "총 범위 유지",
    "Shorten each cage as its incoming gap grows": "앞 간격이 커질수록 각 케이지를 짧게 조정",
    "Parameter": "매개변수",
    "Batch-edit Bend angle": "구부리기 각도 일괄 편집",
    "Batch-edit Bend direction": "구부리기 방향 일괄 편집",
    "Batch-edit Twist angle": "비틀기 각도 일괄 편집",
    "Batch-edit Taper factor": "테이퍼 계수 일괄 편집",
    "Batch-edit Stretch factor": "늘리기 계수 일괄 편집",
    "Enable Stages": "스테이지 활성화",
    "Apply the affected cage stages": "영향받는 케이지 스테이지 적용",
    "Linked shared boundaries are changed only once.": "연동된 공유 경계는 한 번만 변경됩니다.",
    "Cages without this deformation layer are skipped.": "이 변형 레이어가 없는 케이지는 건너뜁니다.",
    "Created {count} cage stages": "케이지 스테이지 {count}개를 만들었습니다",
    "Could not create cage chain: {error}": "케이지 체인을 만들 수 없음: {error}",
    "Only a single cage can be subdivided": "단일 케이지만 세분할 수 있습니다",
    "Set the cage origin to Bottom before subdividing": "세분하기 전에 케이지 원점을 하단으로 설정하세요",
    "Animated cage parameters cannot be subdivided safely": "애니메이션이 있는 케이지 매개변수는 안전하게 세분할 수 없습니다",
    "Taper collapses at an interior split boundary": "테이퍼가 내부 분할 경계에서 붕괴됩니다",
    "Subdivided cage into {count} chained stages": "케이지를 체인 스테이지 {count}개로 세분했습니다",
    "Subdivided cage into {count} chained stages (gap clamped to preserve range)": "케이지를 체인 스테이지 {count}개로 세분했습니다(범위 유지를 위해 간격 제한)",
    "Could not subdivide cage: {error}": "케이지를 세분할 수 없음: {error}",
    "Could not batch edit chain: {error}": "체인을 일괄 편집할 수 없음: {error}",
    "No matching cage values were changed": "일치하는 케이지 값이 변경되지 않았습니다",
    "Updated {count} cage stages": "케이지 스테이지 {count}개를 업데이트했습니다",
    "Fitted {count} cage stages to chain input": "케이지 스테이지 {count}개를 체인 입력에 맞췄습니다",
    "No cage chain metadata was found": "케이지 체인 메타데이터를 찾지 못했습니다",
    "Missing cage stages: {indices}": "누락된 케이지 스테이지: {indices}",
    "Duplicate cage stage indices: {indices}": "중복된 케이지 스테이지 인덱스: {indices}",
    "A non-cage modifier is inserted inside the chain": "체인 안에 케이지가 아닌 수정자가 삽입되어 있습니다",
    "A chain stage has no matching controller": "체인 스테이지에 맞는 컨트롤러가 없습니다",
    "Chain stages use different connection modes": "체인 스테이지의 연결 모드가 서로 다릅니다",
    "Cage chain is broken": "케이지 체인이 끊어져 있습니다",
    "No Cage Chain was found": "케이지 체인을 찾지 못했습니다",
    "Reconnected {count} cage stages": "케이지 스테이지 {count}개를 다시 연결했습니다",
    "Add Cage Chain": "케이지 체인 추가",
    "Number of segments to create": "만들 세그먼트 수",
    "Connection Mode": "연결 모드",
    "How neighboring cage segments handle their boundaries": "인접 케이지 세그먼트가 경계를 처리하는 방식",
    "Continue from each preceding cage": "바로 앞 케이지에서 이어서 계속",
    "Limit each segment to its own box": "각 세그먼트를 자체 상자 안으로 제한",
    "Gap": "간격",
    "Gap Before": "앞 간격",
    "Gap from Previous Cage": "이전 케이지와의 간격",
    "Non-negative distance from the previous cage; changing it keeps the overall chain span when possible": "이전 케이지로부터의 음이 아닌 거리. 변경 시 가능하면 체인 전체 길이를 유지합니다",
    "Distance between this cage and the previous cage": "이 케이지와 이전 케이지 사이의 거리",
    "Distance between neighboring cage frames in target units": "인접 케이지 프레임 사이 거리(대상 단위)",
    "Cage Axis": "케이지 축",
    "Use the longest input dimension": "입력의 가장 긴 치수 사용",
    "Align cage Y to target +X": "케이지 Y를 대상 +X에 맞춤",
    "Align cage Y to target -X": "케이지 Y를 대상 -X에 맞춤",
    "Align cage Y to target +Y": "케이지 Y를 대상 +Y에 맞춤",
    "Align cage Y to target -Y": "케이지 Y를 대상 -Y에 맞춤",
    "Align cage Y to target +Z": "케이지 Y를 대상 +Z에 맞춤",
    "Align cage Y to target -Z": "케이지 Y를 대상 -Z에 맞춤",
    "Select a supported target object first": "먼저 지원되는 대상 오브젝트를 선택하세요",
    "Add Simple Deform": "Simple Deform 추가",
    "Add Simple Deform (Legacy)": "Simple Deform 추가(레거시)",
    "Add a traditional Simple Deform modifier": "기존 Simple Deform 수정자 추가",
    "Added legacy Simple Deform modifier": "레거시 Simple Deform 수정자를 추가했습니다",
    "Cage deformation is not supported for lattice objects": "래티스 오브젝트는 케이지 변형을 지원하지 않습니다",
    "The selected surface could not be converted for cage deformation": "선택한 서피스를 케이지 변형용으로 변환할 수 없습니다",
    "Surface cage deformation requires a mesh conversion": "서피스 케이지 변형에는 메시 변환이 필요합니다",
    "Add Chained Cages": "체인 케이지 추가",
    "Create Cage Chain": "케이지 체인 만들기",
    "Create several related deformation cages in one operation": "관련된 여러 변형 케이지를 한 번에 만들기",
    "Cage Count": "케이지 수",
    "Use isolated boxes": "각 상자 안의 지오메트리에만 영향",
    "Number of chained cages to create": "만들 체인 케이지 수",
    "Connect Ends": "끝단 연결",
    "Align each cage bottom to the previous cage top": "각 케이지 하단을 이전 케이지 상단에 맞춤",
    "Chain Mode": "체인 모드",
    "Use forward continuation when available": "가능하면 전방 연속 사용",
    "Create stages without automatic reconnection": "자동 재연결 없이 스테이지 만들기",
    "Chained": "체인",
    "Independent": "독립",
    "Segment": "세그먼트",
    "Enable Stage": "스테이지 활성화",
    "Temporarily apply or bypass this cage while preserving chained-stage flow": "체인 스테이지 흐름을 유지한 채 이 케이지를 일시 적용하거나 우회",
    "Show Other Cages": "다른 케이지 표시",
    "Display inactive cages and make their viewport controls directly editable": "비활성 케이지를 표시하고 뷰포트 컨트롤을 바로 편집할 수 있게 함",
    "Show Other Cage Controllers": "다른 케이지 컨트롤러 표시",
    "Display all cage controllers except active one": "활성 케이지를 제외한 모든 케이지 컨트롤러 표시",
    "Active Cage": "활성 케이지",
    "Inactive Cage": "비활성 케이지",
    "Active cage is highlighted; other cages are dimmed": "활성 케이지는 강조되고 다른 케이지는 어둡게 표시됩니다",
    "Select this cage stage and its controller": "이 케이지 스테이지와 컨트롤러 선택",
    "Select Cage Stage": "케이지 스테이지 선택",
    "Cage Deform Strength Handle": "케이지 변형 강도 핸들",
    "Cage End Shape": "케이지 끝단 형태",
    "Cage Boundary": "케이지 경계",
    "Auto Reconnect Chain": "체인 자동 재연결",
    "Automatically refresh downstream cage frames after a chain parameter or controller transform changes": "체인 매개변수나 컨트롤러 변형이 바뀌면 하류 케이지 프레임을 자동 새로고침",
    "Auto Reconnect": "자동 재연결",
    "Refresh downstream cage frames after upstream edits": "상류 편집 후 하류 케이지 프레임 새로고침",
    "Use one-sided continuation": "단방향 연속 사용",
    "Propagate each preceding cage output frame to the next cage": "바로 앞 케이지의 출력 프레임을 다음 케이지로 전달",
    "Reconnect Broken Chain": "끊어진 체인 다시 연결",
    "Attempt contiguous stages even when a stack issue is detected": "스택 문제가 감지되어도 연속 스테이지를 시도",
    "Cage Deform core is unavailable": "케이지 변형 코어를 사용할 수 없습니다",
    "Chained Cages": "체인 케이지",
    "Independent Cage Chain": "독립 케이지 체인",
    "Reconnect Chain": "체인 다시 연결",
    "Reconnect Cage Chain": "케이지 체인 다시 연결",
    "Align each cage to the previous cage's output frame": "각 케이지를 이전 케이지의 출력 프레임에 맞춤",
    "Each stage keeps its own angle and length; reconnect updates the incoming frame.": "각 스테이지는 자체 각도와 길이를 유지합니다. 재연결은 입력 프레임만 갱신합니다.",
    "Each stage keeps its deformations, length, and incoming gap.": "각 스테이지는 자체 변형, 길이, 앞 간격을 유지합니다.",
    "Sync Shared End Scale": "공유 끝단 스케일 동기화",
    "Scale both sides of each shared cage seam together while keeping each outer end independent": "각 공유 케이지 이음새 양쪽 스케일을 함께 맞추고 바깥 끝단은 각각 독립 유지",
    "Scale both sides of each shared cage seam together while keeping outer ends independent": "각 공유 케이지 이음새 양쪽 스케일을 함께 맞추고 바깥 끝단은 독립 유지",
    "Only neighboring seam-end scales are synchronized.": "인접 이음새 끝단 스케일만 동기화됩니다.",
    "Outer cage ends remain independent.": "바깥 케이지 끝단은 독립된 채로 유지됩니다.",
    "Chained mode starts at the lower cage boundary.": "체인 모드는 케이지 하단 경계에서 시작합니다.",
    "Cage Chain mode is locked to Chained.": "케이지 체인 모드는 체인으로 고정되어 있습니다.",
    "Keep the prefix unchanged and continue from the cage end": "앞부분은 그대로 두고 케이지 끝의 경향에서 이어감",
    "Simple Deformer": "심플 디포머",
    "Simple Deformer V2": "심플 디포머 V2",
    "Add New Cages to End": "새 케이지를 스택 끝에 추가",
    "Place newly-created cage stages at the end of the modifier stack": "새로 만든 케이지 스테이지를 수정자 스택 끝에 배치",
    "Cage Deform": "케이지 변형",
    "Add Cage Deform": "케이지 변형 추가",
    "Add an independent cage deformation stage": "독립 케이지 변형 스테이지 추가",
    "Added Cage Deform stage": "케이지 변형 스테이지를 추가했습니다",
    "Deform axis changed; the user-supplied Origin was preserved": "변형 축이 변경되었습니다. 사용자 지정 원점은 유지되었습니다",
    "Subdivision was added at the end; move it before Simple Deform": "세분이 끝에 추가되었습니다. Simple Deform 앞으로 옮기세요",
    "Inserted {inserted} Simple Deform keyframe channels": "Simple Deform 키프레임 채널 {inserted}개를 삽입했습니다",
    "Removed {removed} Simple Deform keyframe channels": "Simple Deform 키프레임 채널 {removed}개를 제거했습니다",
    "Independent cage deformation": "독립 케이지 변형",
    "Bend, Twist, Taper, and Stretch.": "구부리기, 비틀기, 테이퍼, 늘리기를 지원합니다.",
    "Combine Bend, Twist, Taper, and Stretch in one cage.": "한 케이지에서 구부리기, 비틀기, 테이퍼, 늘리기를 조합할 수 있습니다.",
    "Cage Stack": "케이지 스택",
    "Move Cage Stage": "케이지 스테이지 이동",
    "Move this deformation earlier or later in the modifier stack": "수정자 스택에서 이 변형을 앞이나 뒤로 이동",
    "Duplicate Cage Stage": "케이지 스테이지 복제",
    "Duplicate": "복제",
    "Remove Cage Stage": "케이지 스테이지 제거",
    "Remove Stage": "스테이지 제거",
    "Remove Cage Stack": "케이지 스택 제거",
    "Remove": "제거",
    "Remove this managed deformation stage and its cage controller": "이 관리 변형 스테이지와 케이지 컨트롤러 제거",
    "Remove every managed cage stage and its owned controllers": "모든 관리 케이지 스테이지와 소유 컨트롤러 제거",
    "Shape": "형태",
    "Deformation Layers": "변형 레이어",
    "Expand All": "모두 펼치기",
    "Add Deformation": "변형 추가",
    "Add Deformation Layer": "변형 레이어 추가",
    "Add one deformation operation to this cage": "이 케이지에 변형 작업 하나 추가",
    "Select Deformation Layer": "변형 레이어 선택",
    "Select this deformation layer without changing its evaluation": "평가 상태를 바꾸지 않고 이 변형 레이어 선택",
    "Remove Deformation Layer": "변형 레이어 제거",
    "Remove this deformation operation from the cage": "이 케이지에서 변형 작업 제거",
    "Toggle Deformation Layer": "변형 레이어 활성 전환",
    "Temporarily bypass or restore this deformation without losing its settings": "설정을 잃지 않고 이 변형을 일시 우회하거나 복원",
    "Move Deformation Layer": "변형 레이어 이동",
    "Move this deformation operation earlier or later": "이 변형 작업을 앞이나 뒤로 이동",
    "Up": "위로",
    "Down": "아래로",
    "Execute this layer earlier": "이 레이어를 더 일찍 실행",
    "Execute this layer later": "이 레이어를 더 늦게 실행",
    "This deformation is already enabled": "이 변형은 이미 활성화되어 있습니다",
    "Deformation Type": "변형 유형",
    "Deformation Types": "변형 유형",
    "Deformations": "변형",
    "Shape operations combined by this cage": "이 케이지가 조합하는 형태 작업",
    "Enable one or more deformation operations in this cage": "이 케이지에서 하나 이상의 변형 작업 활성화",
    "At least one deformation type must remain enabled": "변형 유형은 최소 하나가 활성 상태로 남아 있어야 합니다",
    "Shape operation performed inside the cage": "케이지 안에서 수행하는 형태 작업",
    "Bend": "구부리기",
    "Curve geometry along the cage axis": "케이지 축을 따라 지오메트리를 구부림",
    "Twist": "비틀기",
    "Rotate cross-sections around the cage axis": "단면을 케이지 축 주위로 회전",
    "Taper": "테이퍼",
    "Scale cross-sections along the cage axis": "케이지 축을 따라 단면 스케일",
    "Stretch": "늘리기",
    "Scale geometry along the cage axis": "케이지 축을 따라 지오메트리 스케일",
    "Angle": "각도",
    "Total Bend or Twist angle through the cage length": "케이지 전체 길이에 걸친 구부리기 또는 비틀기 총 각도",
    "Bend Strength": "구부리기 강도",
    "Bend angle through the cage length": "케이지 전체 길이에 걸친 구부리기 각도",
    "Bend Angle": "구부리기 각도",
    "Total Bend angle through the cage length": "케이지 전체 길이에 걸친 구부리기 총 각도",
    "Twist Strength": "비틀기 강도",
    "Twist angle through the cage length": "케이지 전체 길이에 걸친 비틀기 각도",
    "Twist Angle": "비틀기 각도",
    "Total Twist angle through the cage length": "케이지 전체 길이에 걸친 비틀기 총 각도",
    "Taper Factor": "테이퍼 계수",
    "Amount of taper along the cage axis": "케이지 축을 따른 테이퍼 양",
    "Cross-section scale change through the cage length": "케이지 전체 길이에 걸친 단면 스케일 변화량",
    "Stretch Factor": "늘리기 계수",
    "Amount of stretch along the cage axis": "케이지 축을 따른 늘리기 양",
    "Length scale change through the cage": "케이지에 걸친 길이 스케일 변화량",
    "Factor": "계수",
    "Amount used by Taper and Stretch": "테이퍼와 늘리기에 사용하는 양",
    "Direction": "방향",
    "Direction of Bend around the cage axis": "케이지 축 주위 구부리기 방향",
    "Mode": "모드",
    "How geometry outside the cage is handled": "케이지 밖 지오메트리 처리 방식",
    "Limited": "제한",
    "Deform inside; continue outside from the cage ends": "안쪽은 변형하고, 바깥은 케이지 끝에서 이어감",
    "Within Box": "상자 안",
    "Only points inside the cage are affected": "케이지 안 점만 영향을 받습니다",
    "Unlimited": "무제한",
    "Continue deformation beyond the cage": "케이지를 넘어 변형을 계속",
    "Origin": "원점",
    "Starting pattern of the deformation": "변형 시작 패턴",
    "Bottom": "하단",
    "Start at the lower cage boundary": "케이지 하단 경계에서 시작",
    "Center": "중심",
    "Use signed distance from the cage center": "케이지 중심으로부터의 부호 있는 거리 사용",
    "Symmetric": "대칭",
    "Mirror the deformation profile across the center": "변형 프로파일을 중심 기준으로 미러",
    "Top": "상단",
    "Start at the upper cage boundary": "케이지 상단 경계에서 시작",
    "Preserve Volume": "부피 유지",
    "Compensate cross-section size while stretching": "늘릴 때 단면 크기 보정",
    "Cage Controls": "케이지 컨트롤",
    "Deform Axis": "변형 축",
    "Target axis used when aligning and fitting the cage": "케이지 정렬과 맞춤에 사용하는 대상 축",
    "Size": "크기",
    "Dimensions of the independent deformation cage": "독립 변형 케이지의 치수",
    "Auto": "자동",
    "Use the longest local dimension": "가장 긴 로컬 치수 사용",
    "Align & Fit": "정렬 및 맞춤",
    "Align & Fit Chain": "체인 정렬 및 맞춤",
    "Fit to Object": "오브젝트에 맞추기",
    "Fit the active cage, or its entire connected chain, to the geometry entering the deformation": "활성 케이지 또는 연결된 전체 체인을 변형으로 들어오는 지오메트리에 맞춤",
    "Select Cage": "케이지 선택",
    "Select Cage Controller": "케이지 컨트롤러 선택",
    "Return to Object": "오브젝트로 돌아가기",
    "Select the object controlled by this deformation cage": "이 변형 케이지가 제어하는 오브젝트 선택",
    "Edit Cage": "케이지 편집",
    "Select the cage controller and activate a transform tool": "케이지 컨트롤러를 선택하고 변형 도구 활성화",
    "Move": "이동",
    "Move the deformation cage": "변형 케이지 이동",
    "Rotate": "회전",
    "Rotate and aim the deformation cage": "변형 케이지를 회전하고 방향 지정",
    "Scale": "스케일",
    "Resize the deformation cage": "변형 케이지 크기 조정",
    "Show Cage": "케이지 표시",
    "Draw the cyan cage and orange deformation guide": "시안 케이지와 주황 변형 가이드 그리기",
    "Show Axis Switch": "축 전환 표시",
    "Show bend-trend choices around the cage; the choices hide after selection unless Ctrl is held": "케이지 주변에 구부리기 경향 선택지를 표시합니다. 선택 후에는 숨겨지며 Ctrl을 누르면 계속 표시됩니다",
    "Show Bend Direction Handle": "구부리기 방향 핸들 표시",
    "Show a separate ring for adjusting the Bend direction": "구부리기 방향 조정용 독립 링 표시",
    "Axis Switch": "축 전환",
    "Direction Ring": "방향 링",
    "Bend Trend": "구부리기 경향",
    "Fine Direction": "정밀 방향",
    "Helper objects stay hidden until cage transform": "헬퍼 오브젝트는 케이지 변형 시까지 숨김",
    "Numeric Controls": "수치 컨트롤",
    "Show exact cage size, location, and rotation values": "정확한 케이지 크기, 위치, 회전 값 표시",
    "Independent Ends": "독립 끝단",
    "Show separate top and bottom cross-section controls": "상·하 단면 개별 컨트롤 표시",
    "Top Scale": "상단 스케일",
    "Scale the top cage cross-section without changing the bottom": "하단은 그대로 두고 상단 케이지 단면만 스케일",
    "Bottom Scale": "하단 스케일",
    "Scale the bottom cage cross-section without changing the top": "상단은 그대로 두고 하단 케이지 단면만 스케일",
    "Top Offset": "상단 오프셋",
    "Move the top cage cross-section without changing the bottom": "하단은 그대로 두고 상단 케이지 단면만 이동",
    "Bottom Offset": "하단 오프셋",
    "Move the bottom cage cross-section without changing the top": "상단은 그대로 두고 하단 케이지 단면만 이동",
    "Offset": "오프셋",
    "Show Shape Handles": "형태 핸들 표시",
    "Show separate top and bottom cross-section shaping handles": "상·하 단면 개별 성형 핸들 표시",
    "Show Length Handles": "길이 핸들 표시",
    "Show handles that move the top or bottom cage boundary independently": "상단 또는 하단 케이지 경계를 독립적으로 이동하는 핸들 표시",
    "Limit to Object Bounds": "오브젝트 경계 안으로 제한",
    "Prevent the top and bottom cage boundaries from moving beyond the input object's bounds": "상·하 케이지 경계가 입력 오브젝트 경계를 넘지 않도록 함",
    "Length handles stop at the object bounds": "길이 핸들은 오브젝트 경계에서 멈춥니다",
    "Outer length handles stop at the object bounds": "바깥 길이 핸들은 오브젝트 경계에서 멈춥니다",
    "Reset Independent Ends": "독립 끝단 재설정",
    "Restore both cage ends to the fitted cross-section": "양쪽 케이지 끝단을 맞춤 시 단면으로 복원",
    "Cyan top / green bottom: drag one end only": "시안 상단 / 초록 하단: 한쪽 끝단만 드래그",
    "Top End Shape": "상단 끝 형태",
    "Bottom End Shape": "하단 끝 형태",
    "Yellow top / amber bottom: move one boundary": "노랑 상단 / 호박색 하단: 한쪽 경계만 이동",
    "Top Boundary": "상단 경계",
    "Bottom Boundary": "하단 경계",
    "Shared Boundary": "공유 경계",
    "Cage Length": "케이지 길이",
    "Interior boundaries resize both neighboring cages": "내부 경계는 인접한 두 케이지 길이를 함께 조정합니다",
    "Interior boundaries adjust cage length and gap without overlap": "내부 경계는 겹치지 않도록 케이지 길이와 간격을 조정합니다",
    "Drag Along Cage • Shift Precise • Ctrl Snap": "케이지를 따라 드래그 • Shift 정밀 • Ctrl 스냅",
    "Alt Slide X • Shift Precise • Ctrl Snap": "Alt로 X 이동 • Shift 정밀 • Ctrl 스냅",
    "Location": "위치",
    "Rotation": "회전",
    "Orange handle: drag Angle": "주황 핸들: 각도 드래그",
    "Orange handle: drag Factor": "주황 핸들: 계수 드래그",
    "Alt Direction • Shift Precise • Ctrl Snap": "Alt로 방향 • Shift 정밀 • Ctrl 스냅",
    "Shift Precise • Ctrl Snap": "Shift 정밀 • Ctrl 스냅",
    "Drag Around Ring • Shift Precise • Ctrl Snap": "링 주위로 드래그 • Shift 정밀 • Ctrl 스냅",
    "Drag Along Axis • Shift Precise • Ctrl Snap": "축을 따라 드래그 • Shift 정밀 • Ctrl 스냅",
    "Bend Direction": "구부리기 방향",
    "Set Bend Trend": "구부리기 경향 설정",
    "Choose Bend Trend": "구부리기 경향 선택",
    "Choose a signed cage axis and one of its two perpendicular bend trends; hold Ctrl to keep all choices visible": "부호 있는 케이지 축과 그에 수직인 두 구부리기 경향 중 하나를 선택합니다. Ctrl을 누르면 선택지를 계속 표시합니다",
    "Switch Cage Axis": "케이지 축 전환",
    "Axis switch: RGB is X/Y/Z; diamond is +, ring is -": "축 전환: RGB는 X/Y/Z, 마름모는 +, 링은 -",
    "Orange double arrow: drag Bend angle": "주황 양방향 화살표: 구부리기 각도 드래그",
    "Small orange double arrow: drag Bend direction": "작은 주황 양방향 화살표: 구부리기 방향 드래그",
    "Large purple twist arc: drag around its center": "큰 보라 비틀기 호: 중심 주위로 드래그",
    "Red / green arrows: horizontal / vertical bend trend": "빨강 / 초록 화살표: 가로 / 세로 구부리기 경향",
    "Click to choose and close • Ctrl keeps choices open": "클릭하여 선택 후 닫기 • Ctrl로 선택지 유지",
    "Amber taper handle: drag Factor": "호박색 테이퍼 핸들: 계수 드래그",
    "Green stretch handle: drag Factor": "초록 늘리기 핸들: 계수 드래그",
    "Set Deform Axis": "변형 축 설정",
    "Align the cage axis and fit it to the current stage input": "케이지 축을 맞추고 현재 스테이지 입력에 맞춤",
    "Show Toggle Bend Axis Gizmo": "구부리기 축 전환 기즈모 표시",
    "AIGODLIKE Community:小萌新": "AIGODLIKE Community: 小萌新",
    "AIGODLIKE": "AIGODLIKE",
    "Gizmo Property Show Location": "기즈모 속성 표시 위치",
    "You can press the following shortcut keys when dragging values": "값을 드래그하는 동안 다음 단축키를 사용할 수 있습니다",
    "    Wheel:   Switch Origin Ctrl Mode": "    Wheel:   원점 Ctrl 모드 전환",
    "    X,Y,Z:  Switch Modifier Deform Axis": "    X,Y,Z:  수정자 변형 축 전환",
    "    W:       Switch Deform Wireframe Show": "    W:       변형 와이어프레임 표시 전환",
    "    A:       Switch To Select Bend Axis Mode(deform_method=='BEND')": "    A:       구부리기 축 선택 모드로 전환(deform_method=='BEND')",
    "Show Set Axis Button": "축 설정 기즈모 표시",
    "Follow Upper Limit(Red)": "상한 따라가기(빨강)",
    "Follow Lower Limit(Green)": "하한 따라가기(초록)",
    "Lower limit(Green)": "하한(초록)",
    "UP Limits(Red)": "상한(빨강)",
    "Show Deform Wireframe": "변형 와이어프레임 표시",
    "Minimum value between upper and lower limits": "상한과 하한 사이의 최솟값",
    "Upper and lower limit tolerance": "상·하한 허용 오차",
    "Draw Upper and lower limit Bound Box Color": "상·하한 바운드 박스 그리기 색",
    "Upper and lower limit Bound Box Color": "상·하한 바운드 박스 색",
    "Draw Bound Box Color": "바운드 박스 그리기 색",
    "Bound Box": "바운드 박스",
    "Draw Deform Wireframe Color": "변형 와이어프레임 그리기 색",
    "Deform Wireframe": "변형 와이어프레임",
    "Simple Deform visualization adjustment tool": "Simple Deform 시각화 조정 도구",
    "Select an object and the active modifier is Simple Deform": "오브젝트를 선택하고 활성 수정자가 Simple Deform인지 확인",
    "Bound Middle": "바운드 중앙",
    "Add an empty object origin as the rotation axis (if there is an origin, do not add it), and set the origin position as the lower limit during operation": "회전축으로 빈 오브젝트 원점을 추가하고(이미 있으면 추가하지 않음), 조작 중 원점 위치를 하한으로 설정",
    "Add an empty object origin as the rotation axis (if there is an origin, do not add it), and set the origin position as the upper limit during operation": "회전축으로 빈 오브젝트 원점을 추가하고(이미 있으면 추가하지 않음), 조작 중 원점 위치를 상한으로 설정",
    "Add an empty object origin as the rotation axis (if there is an origin, it will not be added), and set the origin position between the upper and lower limits during operation": "회전축으로 빈 오브젝트 원점을 추가하고(이미 있으면 추가하지 않음), 조작 중 원점 위치를 상한과 하한 사이로 설정",
    "Add an empty object origin as the rotation axis (if there is an origin, do not add it), and set the origin position as the position between the bounding boxes during operation": "회전축으로 빈 오브젝트 원점을 추가하고(이미 있으면 추가하지 않음), 조작 중 원점 위치를 바운딩 박스 사이로 설정",
    "No origin operation": "원점 작업 없음",
    "Origin control mode": "원점 컨트롤 모드",
    "Down limit": "하한",
    "Coefficient": "계수",
    "Up limit": "상한",
    "Upper limit": "상한",
    "3D View -> Select an object and the active modifier is simple deformation": "3D 뷰 -> 오브젝트를 선택하고 활성 수정자가 단순 변형인지 확인",
    "3D View: Simple Deform Helper": "3D 뷰: Simple Deform Helper",
    "Simple Deform Helper": "심플 디폼 헬퍼",
    "Tool Options": "도구 옵션",
    "The scaling value of the object is not 1": "오브젝트 스케일 값이 1이 아닙니다",
    "which will cause the deformation of the simple deformation modifier.": "이로 인해 단순 변형 수정자의 결과가 왜곡될 수 있습니다.",
    "Please apply the scaling before deformation.": "변형 전에 스케일을 적용하세요.",
    "Z Rotate": "Z 회전",
    "Simple Deform Animated": "Simple Deform 애니메이션",
    "Simple Deform Property": "Simple Deform 속성",
    "Insert Keyframe": "키프레임 삽입",
    "Remove Keyframe": "키프레임 제거",
    "Show Simple Deform Gizmo": "Simple Deform 기즈모 표시",
    "Simple Deform Stack": "Simple Deform 스택",
    "Show Other Simple Deform Stages": "다른 Simple Deform 스테이지 표시",
    "Draw faint input bounds for other Simple Deform modifiers": "다른 Simple Deform 수정자의 입력 경계를 옅게 그리기",
    "Show Drag Shortcuts in Header": "헤더에 드래그 단축키 표시",
    "Warn About Low Topology": "낮은 토폴로지 경고",
    "Warn when the active deformation axis has too few geometry points": "활성 변형 축의 지오메트리 점이 너무 적을 때 경고",
    "Wireframe Preview FPS": "와이어프레임 미리보기 FPS",
    "Maximum refresh rate for the optional deformed wireframe preview": "선택적 변형 와이어프레임 미리보기의 최대 새로고침 속도",
    "User Origin is protected": "사용자 원점이 보호되어 있습니다",
    "Follow-limit Origin modes are disabled.": "제한 추종 원점 모드가 비활성화되어 있습니다.",
    "Simple Deform needs more segments to bend smoothly.": "Simple Deform을 부드럽게 구부리려면 세그먼트가 더 필요합니다.",
    "Add Subdivision Before Deform": "변형 전에 세분 추가",
    "Add a non-destructive subdivision modifier before the active Simple Deform": "활성 Simple Deform 앞에 비파괴 세분 수정자 추가",
    "Switch Simple Deform Stage": "Simple Deform 스테이지 전환",
    "Make the previous or next Simple Deform modifier active": "이전 또는 다음 Simple Deform 수정자를 활성으로 설정",
})


translations_en_US = {source: source for source in translations_dict}


class TranslationHelper:
    def __init__(self, name: str, data: dict, lang="zh_CN"):
        self.name = name
        self.translations_dict = dict()

        catalogs = (
            data if all(isinstance(value, dict) for value in data.values())
            else {lang: data}
        )
        for locale, catalog in catalogs.items():
            for src, src_trans in catalog.items():
                key = ("Operator", src)
                self.translations_dict.setdefault(locale, {})[key] = src_trans
                key = ("*", src)
                self.translations_dict.setdefault(locale, {})[key] = src_trans

    def register(self):
        try:
            bpy.app.translations.register(self.name, self.translations_dict)
        except ValueError as e:
            _LOGGER.debug("Register Translation failed: %s", e)

    def unregister(self):
        bpy.app.translations.unregister(self.name)


all_language = get_language_list()


def get_language(language):
    if language not in all_language:
        if bpy.app.version < (4, 0, 0):
            return "zh_CN"
        else:
            return "zh_HANS"
    return language


SimpleDeform_CN = TranslationHelper(
    "SimpleDeform_CN",
    {
        "zh_HANS": translations_dict,
        "ja_JP": translations_ja_JP,
        "ko_KR": translations_ko_KR,
        "en_US": translations_en_US,
    },
)


def register():
    SimpleDeform_CN.register()


def unregister():
    SimpleDeform_CN.unregister()
